#!/bin/bash
# ===============================================
# NAJIKA WORLD - ASSET STRUCTURE SCANNER
# ===============================================
# Scannt die gesamte Asset-Ordnerstruktur und erstellt Dokumentation
#
# USAGE:
#   bash scan_assets.sh
#   oder: chmod +x scan_assets.sh && ./scan_assets.sh
#   Output: ASSET_STRUCTURE.md
#
# Author: Claude Code
# Date: 2025-11-05
# ===============================================

OUTPUT_FILE="ASSET_STRUCTURE.md"
ASSET_PATH="./assets"

# Check if assets folder exists
if [ ! -d "$ASSET_PATH" ]; then
    echo "❌ ERROR: Asset folder not found at: $ASSET_PATH"
    echo ""
    echo "Please ensure assets are located at:"
    echo "  Windows: C:\Najika-World\assets\\"
    echo "  Linux: /home/user/Najika_World/assets/"
    exit 1
fi

echo "🔍 Scanning Asset Structure..."
echo "   Path: $ASSET_PATH"
echo ""

# Calculate statistics
echo "📊 Calculating statistics..."
TOTAL_FOLDERS=$(find "$ASSET_PATH" -type d | wc -l)
TOTAL_FILES=$(find "$ASSET_PATH" -type f | wc -l)
TOTAL_SIZE=$(du -sb "$ASSET_PATH" 2>/dev/null | cut -f1)
TOTAL_SIZE_GB=$(echo "scale=2; $TOTAL_SIZE / 1073741824" | bc)

# Start building output
cat > "$OUTPUT_FILE" << EOF
# 📦 NAJIKA WORLD - ASSET STRUCTURE
**Generated:** $(date "+%Y-%m-%d %H:%M:%S")

---

## 📊 OVERVIEW

- **Total Folders:** $TOTAL_FOLDERS
- **Total Files:** $TOTAL_FILES
- **Total Size:** ${TOTAL_SIZE_GB} GB

---

## 🗂️ FILE TYPES

EOF

# Count file types
echo "📂 Analyzing file types..."
find "$ASSET_PATH" -type f -name "*.*" | sed 's/.*\.//' | sort | uniq -c | sort -rn | while read count ext; do
    example=$(find "$ASSET_PATH" -type f -name "*.$ext" | head -1 | xargs basename)
    echo "| \`.$ext\` | $count | $example |" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << EOF

---

## 📁 FOLDER STRUCTURE

\`\`\`text
EOF

# Build tree structure
echo "🌳 Building folder tree..."
tree -L 4 -h --du "$ASSET_PATH" >> "$OUTPUT_FILE" 2>/dev/null || {
    # Fallback if tree command not available
    find "$ASSET_PATH" -type d | head -100 | sed 's|[^/]*/| |g' >> "$OUTPUT_FILE"
}

cat >> "$OUTPUT_FILE" << EOF
\`\`\`

---

## 🎯 KAYKIT PACKS DETECTED

EOF

# Search for KayKit packs
KAYKIT_PACKS=$(find "$ASSET_PATH" -maxdepth 1 -type d -name "KayKit*" 2>/dev/null)

if [ -n "$KAYKIT_PACKS" ]; then
    echo "| Pack Name | Files | Size (GB) | Status |" >> "$OUTPUT_FILE"
    echo "|-----------|-------|-----------|--------|" >> "$OUTPUT_FILE"

    echo "$KAYKIT_PACKS" | while read pack; do
        if [ -d "$pack" ]; then
            pack_name=$(basename "$pack")
            pack_files=$(find "$pack" -type f | wc -l)
            pack_size=$(du -sb "$pack" 2>/dev/null | cut -f1)
            pack_size_gb=$(echo "scale=2; $pack_size / 1073741824" | bc)

            status="✅ OK"
            if [ "$pack_files" -eq 0 ]; then
                status="⚠️ Empty"
            fi

            echo "| \`$pack_name\` | $pack_files | $pack_size_gb | $status |" >> "$OUTPUT_FILE"
        fi
    done
else
    cat >> "$OUTPUT_FILE" << EOF
⚠️ No KayKit packs found. Please ensure assets are properly installed.

Expected packs:
- KayKit_DungeonRemastered_1.1_FREE
- KayKit_Skeletons_1.0_FREE
- KayKit_Adventurers_1.0_FREE
- KayKit_FurnitureBits_1.0_FREE
- KayKit_RestaurantBits_1.0_FREE
- KayKit_HalloweenBits_1.0_FREE
EOF
fi

cat >> "$OUTPUT_FILE" << EOF


---

## 🔧 CONFIG FILES

EOF

# Search for config files
CONFIG_FILES=$(find "$ASSET_PATH" -maxdepth 1 -type f -name "*.json" 2>/dev/null)

if [ -n "$CONFIG_FILES" ]; then
    echo "| File | Size | Status |" >> "$OUTPUT_FILE"
    echo "|------|------|--------|" >> "$OUTPUT_FILE"

    echo "$CONFIG_FILES" | while read config; do
        if [ -f "$config" ]; then
            config_name=$(basename "$config")
            config_size=$(du -k "$config" 2>/dev/null | cut -f1)
            echo "| \`$config_name\` | ${config_size} KB | ✅ Found |" >> "$OUTPUT_FILE"
        fi
    done
else
    cat >> "$OUTPUT_FILE" << EOF
⚠️ **No config files found!**

Expected: \`room_config_detailed.json\`
EOF
fi

cat >> "$OUTPUT_FILE" << EOF


---

## 📝 NOTES

- This structure was automatically generated by scan_assets.sh
- All KayKit assets are CC0 licensed (free to use!)
- Assets are excluded from GitHub due to size (see .gitignore)
- For asset installation instructions, see: ASSETS_DOWNLOAD.md

---

**Generated by:** Claude Code
**Project:** Najika World
**Date:** $(date "+%Y-%m-%d %H:%M:%S")

EOF

echo ""
echo "✅ Asset structure documented!"
echo "   Output: $OUTPUT_FILE"
echo ""
echo "📊 Summary:"
echo "   Folders: $TOTAL_FOLDERS"
echo "   Files: $TOTAL_FILES"
echo "   Size: ${TOTAL_SIZE_GB} GB"
echo ""
