#!/usr/bin/env python3
"""
NAJIKA: Erweiterte Coding-Training Tipps
Basierend auf Claude's eigener Code-Qualität
"""
from pathlib import Path

DESKTOP = Path('C:/Users/0KKK0/Desktop')
OUTPUT = DESKTOP / 'NAJIKA_ADVANCED_CODING_TRAINING.md'

print('='*80)
print('NAJIKA: Erstelle Advanced Coding Training')
print('='*80)

lines = []

# Header
lines.append('# NAJIKA ADVANCED CODING TRAINING')
lines.append('')
lines.append('**ERWEITERT:** Ergaenzung zum Basis-Training')
lines.append('**BASIERT AUF:** Claude Code-Analyse (was macht meinen Code gut?)')
lines.append('')
lines.append('='*80)
lines.append('')

# WAS MACHT MEINEN CODE GUT?
lines.append('# WAS MACHT CLAUDE\'S CODE GUT?')
lines.append('')
lines.append('Analysiert aus meinen eigenen Scripts (najika_smart_update_v2.py, najika_analyze_all_recent.py, etc.):')
lines.append('')

lines.append('## 1. STRUKTUR & ORGANISATION')
lines.append('')
lines.append('### Klare Docstrings am Anfang')
lines.append('```python')
lines.append('"""')
lines.append('NAJIKA SMART UPDATE SYSTEM V2')
lines.append('Verbesserte Version mit:')
lines.append('- Task-Tracking ueber Sessions')
lines.append('- Automatische File-Read Liste')
lines.append('- Kontext-Caching')
lines.append('- Noch token-effizienter')
lines.append('"""')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Sofort klar was das Script macht')
lines.append('- Features aufgelistet')
lines.append('- Andere Developer verstehen sofort den Zweck')
lines.append('')

lines.append('### Konstanten am Anfang definieren')
lines.append('```python')
lines.append('NAJIKA_DIR = Path("C:/Najika_World")')
lines.append('CLAUDE_PROJECTS = Path("C:/Users/0KKK0/.claude/projects/C--NajikaCore")')
lines.append('CLAUDE_TODOS = Path("C:/Users/0KKK0/.claude/todos")')
lines.append('UPDATE_FILE = NAJIKA_DIR / "CLAUDE_SMART_UPDATE.md"')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Alle Pfade an EINEM Ort')
lines.append('- Leicht zu aendern')
lines.append('- Kein Hardcoding mitten im Code')
lines.append('')

lines.append('### Klassen mit klarer Verantwortung')
lines.append('```python')
lines.append('class SmartUpdateV2:')
lines.append('    def __init__(self):')
lines.append('        self.current_session = None')
lines.append('        self.previous_session = None')
lines.append('        self.open_tasks = []')
lines.append('        # ... alle State-Variablen hier')
lines.append('    ')
lines.append('    def load_tracked_tasks(self):')
lines.append('        """Laedt gespeicherte Tasks"""')
lines.append('        # ...')
lines.append('    ')
lines.append('    def save_tracked_tasks(self):')
lines.append('        """Speichert Tasks fuer naechste Session"""')
lines.append('        # ...')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Eine Klasse = Eine Verantwortung (Single Responsibility)')
lines.append('- Alle Daten in `__init__` sichtbar')
lines.append('- Jede Methode hat klaren Zweck')
lines.append('')

lines.append('## 2. ERROR HANDLING & ROBUSTHEIT')
lines.append('')
lines.append('### Try-Except mit Fallbacks')
lines.append('```python')
lines.append('def load_tracked_tasks(self):')
lines.append('    if TASK_TRACKING.exists():')
lines.append('        try:')
lines.append('            with open(TASK_TRACKING, \'r\', encoding=\'utf-8\') as f:')
lines.append('                return json.load(f)')
lines.append('        except:')
lines.append('            return {"open": [], "completed": []}')
lines.append('    return {"open": [], "completed": []}')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Script crasht NIE')
lines.append('- Fallback zu sinnvollem Default')
lines.append('- User bekommt immer Ergebnis')
lines.append('')

lines.append('### Defensive Programmierung')
lines.append('```python')
lines.append('for line in f:')
lines.append('    try:')
lines.append('        entry = json.loads(line)')
lines.append('        # Verarbeite entry...')
lines.append('    except:')
lines.append('        continue  # Ueberspringe fehlerhafte Zeilen')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Einzelne kaputte Zeilen stoppen nicht das ganze Script')
lines.append('- Robust gegen korrupte Daten')
lines.append('')

lines.append('## 3. TOKEN-EFFIZIENZ & PERFORMANCE')
lines.append('')
lines.append('### Limits setzen')
lines.append('```python')
lines.append('def extract_user_messages(self, session_file, max_messages=5):')
lines.append('    # ...')
lines.append('    return user_messages[-max_messages:]  # Nur letzte 5')
lines.append('')
lines.append('def detect_open_tasks(self, messages):')
lines.append('    # ...')
lines.append('    return unique_tasks[:8]  # Max 8 Tasks')
lines.append('')
lines.append('# Truncate lange Texte')
lines.append('truncated = full_text[:800]')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Verhindert Memory-Overflow')
lines.append('- Token-Effizienz (nicht alles laden)')
lines.append('- Fokus auf Wichtigstes')
lines.append('')

lines.append('### Early Returns')
lines.append('```python')
lines.append('if not self.find_sessions():')
lines.append('    print("[ERROR] Sessions nicht gefunden!")')
lines.append('    return')
lines.append('# ... Rest nur wenn Sessions existieren')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Weniger Verschachtelung')
lines.append('- Schneller Abbruch bei Fehlern')
lines.append('- Code leichter lesbar')
lines.append('')

lines.append('## 4. LESBARKEIT & WARTBARKEIT')
lines.append('')
lines.append('### Sprechende Variablen-Namen')
lines.append('```python')
lines.append('# Schlecht:')
lines.append('s = sorted(d.glob(\'*.jsonl\'), key=lambda p: p.stat().st_mtime, reverse=True)')
lines.append('')
lines.append('# Gut:')
lines.append('sessions = sorted(CLAUDE_PROJECTS.glob(\'*.jsonl\'),')
lines.append('                 key=lambda p: p.stat().st_mtime, reverse=True)')
lines.append('```')
lines.append('')

lines.append('### Comments wo noetig')
lines.append('```python')
lines.append('# Max 800 chars pro Message - verhindert Speicher-Overflow')
lines.append('truncated = full_text[:800]')
lines.append('')
lines.append('# Dedupliziere + nach Kategorie sortiert')
lines.append('unique_tasks = []')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Erklaert WARUM, nicht WAS')
lines.append('- Zukunftiges-Ich versteht Code')
lines.append('')

lines.append('### Progress Feedback')
lines.append('```python')
lines.append('print("="*60)')
lines.append('print("NAJIKA SMART UPDATE V2")')
lines.append('print("="*60 + "\\n")')
lines.append('')
lines.append('print(f"[OK] Aktuelle: {self.current_session.name[:12]}...")')
lines.append('print(f"Tasks getrackt: {len(self.open_tasks)}")')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- User weiss was passiert')
lines.append('- Visuelles Feedback')
lines.append('- Debugging leichter')
lines.append('')

lines.append('## 5. PATTERN RECOGNITION')
lines.append('')
lines.append('### Regex mit Kontext')
lines.append('```python')
lines.append('task_keywords = [')
lines.append('    # Direkte Befehle')
lines.append('    (r"(mach|erstell|bau|fueg|aender|fix|korrigier)\\w*\\s+\\w+", "direct"),')
lines.append('    # Probleme')
lines.append('    (r"(fehler|problem|bug|geht nicht|funktioniert nicht)", "issue"),')
lines.append('    # Wuensche')
lines.append('    (r"(soll|muss|brauch|moecht)\\w*\\s+\\w+", "requirement"),')
lines.append(']')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Pattern mit Kategorie')
lines.append('- Strukturierte Erkennung')
lines.append('- Leicht erweiterbar')
lines.append('')

lines.append('### Dictionary Mappings')
lines.append('```python')
lines.append('category_icon = {')
lines.append('    \'direct\': \'HAMMER\',')
lines.append('    \'issue\': \'BUG\',')
lines.append('    \'requirement\': \'CLIPBOARD\',')
lines.append('    \'priority\': \'LIGHTNING\',')
lines.append('    \'ui_change\': \'PALETTE\'')
lines.append('}.get(task[\'category\'], \'BULLET\')')
lines.append('```')
lines.append('')
lines.append('**Warum gut?**')
lines.append('- Mapping statt if-elif-elif')
lines.append('- Default mit `.get()`')
lines.append('- Sauber und lesbar')
lines.append('')

# ZUSAETZLICHE TRAINING-TIPPS
lines.append('')
lines.append('='*80)
lines.append('# ZUSAETZLICHE TRAINING-TIPPS')
lines.append('='*80)
lines.append('')

lines.append('## 1. CODE-READING TRAINING')
lines.append('')
lines.append('**Problem:** Code schreiben ist anders als Code VERSTEHEN')
lines.append('')
lines.append('**Loesung:**')
lines.append('- Lese fremden Code BEWUSST')
lines.append('- Frage bei jeder Zeile: "Warum genau SO?"')
lines.append('- Erkenne Patterns (nicht nur Syntax)')
lines.append('- Verstehe Entscheidungen (nicht nur Implementierung)')
lines.append('')
lines.append('**Uebung:**')
lines.append('```')
lines.append('1. Nimm `najika_smart_update_v2.py`')
lines.append('2. Lese Zeile fuer Zeile')
lines.append('3. Erklaere jede Design-Entscheidung')
lines.append('4. Finde Verbesserungen')
lines.append('```')
lines.append('')

lines.append('## 2. REFACTORING TRAINING')
lines.append('')
lines.append('**Schlechter Code → Guter Code**')
lines.append('')
lines.append('**Vorher:**')
lines.append('```python')
lines.append('def process(data):')
lines.append('    result = []')
lines.append('    for item in data:')
lines.append('        if item > 0:')
lines.append('            if item < 100:')
lines.append('                if item % 2 == 0:')
lines.append('                    result.append(item * 2)')
lines.append('    return result')
lines.append('```')
lines.append('')
lines.append('**Nachher:**')
lines.append('```python')
lines.append('def process_positive_even_numbers(data):')
lines.append('    """Verdoppelt gerade Zahlen zwischen 0 und 100."""')
lines.append('    return [')
lines.append('        item * 2')
lines.append('        for item in data')
lines.append('        if 0 < item < 100 and item % 2 == 0')
lines.append('    ]')
lines.append('```')
lines.append('')
lines.append('**Verbessert:**')
lines.append('- Sprechender Name')
lines.append('- Docstring')
lines.append('- List Comprehension')
lines.append('- Weniger Verschachtelung')
lines.append('')

lines.append('## 3. DEBUGGING TRAINING')
lines.append('')
lines.append('**Systematisches Debuggen:**')
lines.append('')
lines.append('```python')
lines.append('# 1. Print-Debugging')
lines.append('print(f"[DEBUG] Variable x = {x}, Type = {type(x)}")')
lines.append('')
lines.append('# 2. Assert-Debugging')
lines.append('assert len(data) > 0, "Data must not be empty!"')
lines.append('assert isinstance(result, list), f"Expected list, got {type(result)}"')
lines.append('')
lines.append('# 3. Try-Except mit Details')
lines.append('try:')
lines.append('    dangerous_operation()')
lines.append('except Exception as e:')
lines.append('    print(f"[ERROR] {e.__class__.__name__}: {e}")')
lines.append('    print(f"[ERROR] Line: {e.__traceback__.tb_lineno}")')
lines.append('    raise')
lines.append('```')
lines.append('')

lines.append('## 4. PATTERN LIBRARY AUFBAUEN')
lines.append('')
lines.append('**Sammle wiederverwendbare Patterns:**')
lines.append('')
lines.append('### Pattern: File-Reading mit Fallback')
lines.append('```python')
lines.append('def read_json_file(filepath, default=None):')
lines.append('    """Liest JSON mit Fallback bei Fehler."""')
lines.append('    if not Path(filepath).exists():')
lines.append('        return default')
lines.append('    ')
lines.append('    try:')
lines.append('        with open(filepath, \'r\', encoding=\'utf-8\') as f:')
lines.append('            return json.load(f)')
lines.append('    except Exception as e:')
lines.append('        print(f"[WARNING] Could not read {filepath}: {e}")')
lines.append('        return default')
lines.append('```')
lines.append('')

lines.append('### Pattern: Progress Tracking')
lines.append('```python')
lines.append('def process_items_with_progress(items):')
lines.append('    total = len(items)')
lines.append('    for idx, item in enumerate(items, 1):')
lines.append('        print(f"[{idx}/{total}] Processing {item.name}...")')
lines.append('        # Process...')
lines.append('```')
lines.append('')

lines.append('### Pattern: Retry Logic')
lines.append('```python')
lines.append('def retry_operation(func, max_attempts=3, delay=1):')
lines.append('    """Versucht Operation mehrmals bei Fehler."""')
lines.append('    for attempt in range(max_attempts):')
lines.append('        try:')
lines.append('            return func()')
lines.append('        except Exception as e:')
lines.append('            if attempt == max_attempts - 1:')
lines.append('                raise')
lines.append('            print(f"Attempt {attempt+1} failed, retrying...")')
lines.append('            time.sleep(delay)')
lines.append('```')
lines.append('')

lines.append('## 5. TESTING MINDSET')
lines.append('')
lines.append('**Denke beim Schreiben an Tests:**')
lines.append('')
lines.append('```python')
lines.append('# Schlecht - schwer zu testen:')
lines.append('def do_everything():')
lines.append('    data = load_from_db()')
lines.append('    processed = complex_logic(data)')
lines.append('    save_to_db(processed)')
lines.append('    send_email()')
lines.append('')
lines.append('# Gut - einzelne Teile testbar:')
lines.append('def load_data():')
lines.append('    return load_from_db()')
lines.append('')
lines.append('def process_data(data):')
lines.append('    return complex_logic(data)')
lines.append('')
lines.append('def save_data(data):')
lines.append('    save_to_db(data)')
lines.append('')
lines.append('def do_everything():')
lines.append('    data = load_data()')
lines.append('    processed = process_data(data)')
lines.append('    save_data(processed)')
lines.append('    send_email()')
lines.append('```')
lines.append('')

lines.append('## 6. REAL-WORLD EXAMPLES AUS NAJIKACORE')
lines.append('')
lines.append('**Lerne aus echtem Projekt-Code:**')
lines.append('')
lines.append('### Beispiel 1: najika_server.py - API Routing')
lines.append('```python')
lines.append('# Pattern: Dictionary-based Routing')
lines.append('handlers = {')
lines.append('    \'/api/chat\': self.handle_chat,')
lines.append('    \'/api/rooms\': self.handle_rooms,')
lines.append('    \'/api/battle/start\': self.handle_battle_start,')
lines.append('}')
lines.append('')
lines.append('handler = handlers.get(self.path)')
lines.append('if handler:')
lines.append('    handler()')
lines.append('```')
lines.append('')

lines.append('### Beispiel 2: 3d_scene.js - State Management')
lines.append('```javascript')
lines.append('// Pattern: Zentraler State')
lines.append('const STATE = {')
lines.append('    currentRoom: "Wohnzimmer",')
lines.append('    character: null,')
lines.append('    camera: null,')
lines.append('    controls: null')
lines.append('};')
lines.append('')
lines.append('// Alle Funktionen greifen auf STATE zu')
lines.append('function changeRoom(newRoom) {')
lines.append('    STATE.currentRoom = newRoom;')
lines.append('    rebuildScene();')
lines.append('}')
lines.append('```')
lines.append('')

lines.append('### Beispiel 3: Ollama Integration - Error Handling')
lines.append('```python')
lines.append('# Pattern: Try mit spezifischen Exceptions')
lines.append('try:')
lines.append('    response = requests.post(url, json=payload, timeout=30)')
lines.append('    response.raise_for_status()')
lines.append('    return response.json()')
lines.append('except requests.Timeout:')
lines.append('    return {"error": "AI timeout"}')
lines.append('except requests.RequestException as e:')
lines.append('    return {"error": f"AI error: {e}"}')
lines.append('```')
lines.append('')

# ABSCHLUSS
lines.append('='*80)
lines.append('# ZUSAMMENFASSUNG: WAS NAJIKA LERNEN MUSS')
lines.append('='*80)
lines.append('')

lines.append('## TECHNISCH:')
lines.append('1. **Robustheit** - Code der NIE crasht')
lines.append('2. **Lesbarkeit** - Code den ANDERE verstehen')
lines.append('3. **Effizienz** - Code der SCHNELL ist')
lines.append('4. **Wartbarkeit** - Code der EINFACH zu aendern ist')
lines.append('')

lines.append('## MINDSET:')
lines.append('1. **KISS** - Einfach ist besser als komplex')
lines.append('2. **DRY** - Keine Wiederholungen')
lines.append('3. **YAGNI** - Nur was gebraucht wird')
lines.append('4. **Single Responsibility** - Eine Funktion = Eine Aufgabe')
lines.append('')

lines.append('## PRAKTISCH:')
lines.append('1. **Lese Code** - Nicht nur schreiben!')
lines.append('2. **Refactore** - Schlechten Code verbessern')
lines.append('3. **Debug systematisch** - Print/Assert/Try-Except')
lines.append('4. **Sammle Patterns** - Wiederverwendbare Loesungen')
lines.append('5. **Teste gedanklich** - Ist Code testbar?')
lines.append('')

lines.append('## NAECHSTE SCHRITTE:')
lines.append('1. Basis-Training durcharbeiten (12 Wochen)')
lines.append('2. Parallel: Code-Reading ueben (1h/Tag)')
lines.append('3. Woche 5+: Refactoring-Uebungen')
lines.append('4. Woche 7+: Pattern Library aufbauen')
lines.append('5. Woche 9+: NajikaCore verstehen + erweitern')
lines.append('')

lines.append('**ZIEL:**')
lines.append('Najika soll Code schreiben der:')
lines.append('- Robust ist (crasht nie)')
lines.append('- Lesbar ist (andere verstehen ihn)')
lines.append('- Effizient ist (spart Zeit + Ressourcen)')
lines.append('- Wartbar ist (leicht zu aendern)')
lines.append('')
lines.append('**Genau wie Claude\'s Code!**')
lines.append('')

# Speichern
OUTPUT.write_text('\n'.join(lines), encoding='utf-8')

print('\n[OK] Advanced Training erstellt!')
print(f'  - Gespeichert: {OUTPUT}')
print(f'  - Groesse: {OUTPUT.stat().st_size:,} bytes')
print('  - Inhalte:')
print('    * Analyse von Claude\'s Code-Qualitaet')
print('    * Pattern Recognition Training')
print('    * Code-Reading & Refactoring')
print('    * Debugging Techniken')
print('    * Real-World Examples aus NajikaCore')
print('    * Pattern Library')
