#!/usr/bin/env python3
"""
NAJIKA: Erstelle Coding-Training Dokumentation
Verse + Python + Java + Methodik
"""
from pathlib import Path

DESKTOP = Path('C:/Users/0KKK0/Desktop')
OUTPUT = DESKTOP / 'NAJIKA_CODING_TRAINING_KOMPLETT.md'

print('='*80)
print('NAJIKA: Erstelle Coding-Training Dokumentation')
print('='*80)

lines = []

# Header
lines.append('# NAJIKA CODING TRAINING - KOMPLETT')
lines.append('')
lines.append('**ERSTELLT:** 2025-10-19')
lines.append('**ZWECK:** Training fuer Najika - Verstehen + Anwenden von Code')
lines.append('**SPRACHEN:** Verse, Python, Java')
lines.append('')
lines.append('='*80)
lines.append('')

# TEIL 1: VERSE PROGRAMMIERUNG
lines.append('')
lines.append('# TEIL 1: VERSE PROGRAMMIERUNG')
lines.append('')
lines.append('## Was ist Verse?')
lines.append('')
lines.append('**Verse** ist eine Programmiersprache von Epic Games fuer:')
lines.append('- Unreal Editor for Fortnite (UEFN)')
lines.append('- Fortnite Creative')
lines.append('- Game Development')
lines.append('')
lines.append('**Besonderheiten:**')
lines.append('- Functional Logic Programming')
lines.append('- Static Typed (Typen muessen angegeben werden)')
lines.append('- Object-Oriented (Klassen + Objekte)')
lines.append('- Immutable by Default (Daten aendern sich nicht automatisch)')
lines.append('- Failable Expressions (statt true/false)')
lines.append('- Deterministic (gleiche Eingabe = gleiche Ausgabe)')
lines.append('')
lines.append('**Entwickelt von:**')
lines.append('- Simon Peyton Jones (bekannter Programmiersprachen-Forscher)')
lines.append('- Tim Sweeney (CEO Epic Games)')
lines.append('- Veroeffentlicht: Maerz 2023')
lines.append('')

lines.append('## Verse Syntax Grundlagen')
lines.append('')
lines.append('### 1. Variablen')
lines.append('')
lines.append('```verse')
lines.append('# Immutable (kann nicht geaendert werden)')
lines.append('Name:string = "Najika"')
lines.append('Age:int = 19')
lines.append('')
lines.append('# Mutable (kann geaendert werden)')
lines.append('var Health:int = 100')
lines.append('set Health = 90  # Aendern')
lines.append('```')
lines.append('')
lines.append('**Regel:** Nutze `var` nur wenn du den Wert aendern musst!')
lines.append('')

lines.append('### 2. Types (Datentypen)')
lines.append('')
lines.append('```verse')
lines.append('# Basis-Typen')
lines.append('MyInt:int = 42')
lines.append('MyFloat:float = 3.14')
lines.append('MyString:string = "Hello"')
lines.append('MyBool:logic = true  # in Verse heisst es "logic" nicht "bool"')
lines.append('')
lines.append('# Vector (fuer 3D Position)')
lines.append('Position:vector3 = vector3{X:=0.0, Y:=0.0, Z:=0.0}')
lines.append('```')
lines.append('')

lines.append('### 3. Functions (Funktionen)')
lines.append('')
lines.append('```verse')
lines.append('# Einfache Funktion')
lines.append('SayHello():void =')
lines.append('    Print("Hello, Najika!")')
lines.append('')
lines.append('# Funktion mit Parameter und Rueckgabe')
lines.append('AddNumbers(A:int, B:int):int =')
lines.append('    A + B')
lines.append('')
lines.append('# Funktion mit failable (kann fehlschlagen)')
lines.append('FindPlayer(PlayerID:int)<decides>:player =')
lines.append('    # ... gibt player zurueck wenn gefunden')
lines.append('    # ... schlaegt fehl wenn nicht gefunden')
lines.append('```')
lines.append('')
lines.append('**Wichtig:** `<decides>` bedeutet Funktion kann fehlschlagen!')
lines.append('')

lines.append('### 4. Classes (Klassen)')
lines.append('')
lines.append('```verse')
lines.append('# Basis-Klasse fuer UEFN Devices')
lines.append('my_device := class(creative_device):')
lines.append('    # Variablen')
lines.append('    var Score:int = 0')
lines.append('    ')
lines.append('    # Funktion die beim Start ausgefuehrt wird')
lines.append('    OnBegin<override>()<suspends>:void =')
lines.append('        Print("Device started!")')
lines.append('        IncrementScore()')
lines.append('    ')
lines.append('    # Eigene Funktion')
lines.append('    IncrementScore():void =')
lines.append('        set Score = Score + 1')
lines.append('```')
lines.append('')
lines.append('**`<suspends>`** bedeutet Funktion kann Zeit brauchen (z.B. warten)')
lines.append('')

lines.append('### 5. Control Flow')
lines.append('')
lines.append('```verse')
lines.append('# If-Ausdruck (mit failable)')
lines.append('CheckHealth(HP:int):void =')
lines.append('    if (HP > 50):')
lines.append('        Print("Healthy")')
lines.append('    else if (HP > 20):')
lines.append('        Print("Wounded")')
lines.append('    else:')
lines.append('        Print("Critical")')
lines.append('')
lines.append('# Loop (Schleife)')
lines.append('CountToTen():void =')
lines.append('    for (I := 1..10):')
lines.append('        Print("Count: {I}")')
lines.append('```')
lines.append('')

lines.append('### 6. Events')
lines.append('')
lines.append('```verse')
lines.append('my_game_device := class(creative_device):')
lines.append('    OnBegin<override>()<suspends>:void =')
lines.append('        # Subscribe to Event')
lines.append('        GetPlayspace().PlayerAddedEvent().Subscribe(OnPlayerAdded)')
lines.append('    ')
lines.append('    OnPlayerAdded(Player:player):void =')
lines.append('        Print("Player joined: {Player}")')
lines.append('```')
lines.append('')

lines.append('## Verse Best Practices')
lines.append('')
lines.append('1. **Immutable First**: Nutze `var` nur wenn noetig')
lines.append('2. **Type Safety**: Gib immer Typen an')
lines.append('3. **Failable Expressions**: Nutze `<decides>` fuer Funktionen die fehlschlagen koennen')
lines.append('4. **Event-Driven**: Nutze Events statt Polling')
lines.append('5. **Deterministic**: Gleiche Eingabe muss gleiche Ausgabe geben')
lines.append('')

# TEIL 2: PYTHON PROGRAMMIERUNG
lines.append('')
lines.append('='*80)
lines.append('# TEIL 2: PYTHON PROGRAMMIERUNG')
lines.append('='*80)
lines.append('')
lines.append('## Was ist Python?')
lines.append('')
lines.append('**Python** ist eine der beliebtesten Programmiersprachen:')
lines.append('- Einfach zu lernen')
lines.append('- Vielseitig (Web, AI, Games, Scripts, Data Science)')
lines.append('- Grosse Community')
lines.append('- Viele Libraries')
lines.append('')
lines.append('**Besonderheiten:**')
lines.append('- Dynamically Typed (keine Typ-Angaben noetig)')
lines.append('- Interpreted (kein Kompilieren noetig)')
lines.append('- Object-Oriented + Functional')
lines.append('- Indentation-Based (Einrueckung ist wichtig!)')
lines.append('')

lines.append('## Python Syntax Grundlagen')
lines.append('')
lines.append('### 1. Variablen')
lines.append('')
lines.append('```python')
lines.append('# Keine Typ-Angabe noetig')
lines.append('name = "Najika"')
lines.append('age = 19')
lines.append('health = 100.0')
lines.append('is_active = True')
lines.append('')
lines.append('# Aber du kannst Type Hints nutzen (empfohlen!)')
lines.append('name: str = "Najika"')
lines.append('age: int = 19')
lines.append('```')
lines.append('')

lines.append('### 2. Types (Datentypen)')
lines.append('')
lines.append('```python')
lines.append('# Basis-Typen')
lines.append('my_int: int = 42')
lines.append('my_float: float = 3.14')
lines.append('my_string: str = "Hello"')
lines.append('my_bool: bool = True')
lines.append('')
lines.append('# Collections')
lines.append('my_list: list = [1, 2, 3]  # Veraenderbar')
lines.append('my_tuple: tuple = (1, 2, 3)  # Unveraenderbar')
lines.append('my_dict: dict = {"name": "Najika", "age": 19}')
lines.append('my_set: set = {1, 2, 3}  # Keine Duplikate')
lines.append('```')
lines.append('')

lines.append('### 3. Functions (Funktionen)')
lines.append('')
lines.append('```python')
lines.append('# Einfache Funktion')
lines.append('def say_hello():')
lines.append('    print("Hello, Najika!")')
lines.append('')
lines.append('# Mit Parametern + Rueckgabe')
lines.append('def add_numbers(a: int, b: int) -> int:')
lines.append('    return a + b')
lines.append('')
lines.append('# Mit Default-Parameter')
lines.append('def greet(name: str = "World") -> str:')
lines.append('    return f"Hello, {name}!"')
lines.append('')
lines.append('# Lambda (anonyme Funktion)')
lines.append('square = lambda x: x * x')
lines.append('print(square(5))  # 25')
lines.append('```')
lines.append('')

lines.append('### 4. Classes (Klassen)')
lines.append('')
lines.append('```python')
lines.append('class Character:')
lines.append('    # Constructor')
lines.append('    def __init__(self, name: str, hp: int):')
lines.append('        self.name = name')
lines.append('        self.hp = hp')
lines.append('    ')
lines.append('    # Methode')
lines.append('    def take_damage(self, damage: int):')
lines.append('        self.hp -= damage')
lines.append('        print(f"{self.name} took {damage} damage! HP: {self.hp}")')
lines.append('    ')
lines.append('    # Property')
lines.append('    @property')
lines.append('    def is_alive(self) -> bool:')
lines.append('        return self.hp > 0')
lines.append('')
lines.append('# Nutzung')
lines.append('najika = Character("Najika", 100)')
lines.append('najika.take_damage(20)')
lines.append('```')
lines.append('')

lines.append('### 5. Control Flow')
lines.append('')
lines.append('```python')
lines.append('# If-Else')
lines.append('hp = 75')
lines.append('if hp > 50:')
lines.append('    print("Healthy")')
lines.append('elif hp > 20:')
lines.append('    print("Wounded")')
lines.append('else:')
lines.append('    print("Critical")')
lines.append('')
lines.append('# For-Loop')
lines.append('for i in range(10):')
lines.append('    print(f"Count: {i}")')
lines.append('')
lines.append('# While-Loop')
lines.append('count = 0')
lines.append('while count < 5:')
lines.append('    print(count)')
lines.append('    count += 1')
lines.append('')
lines.append('# List Comprehension (eleganter Loop)')
lines.append('squares = [x*x for x in range(10)]')
lines.append('```')
lines.append('')

lines.append('### 6. Error Handling')
lines.append('')
lines.append('```python')
lines.append('try:')
lines.append('    result = 10 / 0')
lines.append('except ZeroDivisionError as e:')
lines.append('    print(f"Error: {e}")')
lines.append('except Exception as e:')
lines.append('    print(f"Unexpected error: {e}")')
lines.append('finally:')
lines.append('    print("Cleanup")')
lines.append('```')
lines.append('')

lines.append('## Python Best Practices (PEP 8)')
lines.append('')
lines.append('1. **Naming Conventions:**')
lines.append('   - `snake_case` fuer Variablen + Funktionen')
lines.append('   - `PascalCase` fuer Klassen')
lines.append('   - `SCREAMING_SNAKE_CASE` fuer Konstanten')
lines.append('')
lines.append('2. **Indentation:** 4 Leerzeichen (keine Tabs!)')
lines.append('')
lines.append('3. **Line Length:** Max 79 Zeichen')
lines.append('')
lines.append('4. **Imports:**')
lines.append('   ```python')
lines.append('   # Standard library')
lines.append('   import os')
lines.append('   import sys')
lines.append('   ')
lines.append('   # Third party')
lines.append('   import requests')
lines.append('   ')
lines.append('   # Local')
lines.append('   from .my_module import my_function')
lines.append('   ```')
lines.append('')
lines.append('5. **Type Hints:** Nutze sie! (Python 3.5+)')
lines.append('   ```python')
lines.append('   def process_data(items: list[str]) -> dict[str, int]:')
lines.append('       return {item: len(item) for item in items}')
lines.append('   ```')
lines.append('')
lines.append('6. **Docstrings:**')
lines.append('   ```python')
lines.append('   def complex_function(param1: int, param2: str) -> bool:')
lines.append('       """')
lines.append('       Kurze Beschreibung.')
lines.append('       ')
lines.append('       Args:')
lines.append('           param1: Beschreibung')
lines.append('           param2: Beschreibung')
lines.append('       ')
lines.append('       Returns:')
lines.append('           Beschreibung des Rueckgabewerts')
lines.append('       """')
lines.append('       pass')
lines.append('   ```')
lines.append('')

# TEIL 3: JAVA PROGRAMMIERUNG
lines.append('')
lines.append('='*80)
lines.append('# TEIL 3: JAVA PROGRAMMIERUNG')
lines.append('='*80)
lines.append('')
lines.append('## Was ist Java?')
lines.append('')
lines.append('**Java** ist eine der wichtigsten Programmiersprachen:')
lines.append('- Enterprise Software')
lines.append('- Android Apps')
lines.append('- Minecraft')
lines.append('- Web Applications')
lines.append('')
lines.append('**Besonderheiten:**')
lines.append('- Static Typed (Typen muessen angegeben werden)')
lines.append('- Compiled (muss kompiliert werden)')
lines.append('- Object-Oriented (alles ist ein Objekt)')
lines.append('- Platform Independent (Java Virtual Machine)')
lines.append('- "Write Once, Run Anywhere"')
lines.append('')

lines.append('## Java Syntax Grundlagen')
lines.append('')
lines.append('### 1. Variablen')
lines.append('')
lines.append('```java')
lines.append('// Basis-Variablen')
lines.append('String name = "Najika";')
lines.append('int age = 19;')
lines.append('double health = 100.0;')
lines.append('boolean isActive = true;')
lines.append('')
lines.append('// Final (unveraenderbar)')
lines.append('final String GAME_NAME = "NajikaCore";')
lines.append('```')
lines.append('')

lines.append('### 2. Types (Datentypen)')
lines.append('')
lines.append('```java')
lines.append('// Primitive Types')
lines.append('int myInt = 42;')
lines.append('double myDouble = 3.14;')
lines.append('boolean myBool = true;')
lines.append('char myChar = \'A\';')
lines.append('')
lines.append('// Reference Types')
lines.append('String myString = "Hello";')
lines.append('Integer myInteger = 42;  // Wrapper class')
lines.append('')
lines.append('// Arrays')
lines.append('int[] numbers = {1, 2, 3};')
lines.append('String[] names = new String[10];')
lines.append('')
lines.append('// Collections')
lines.append('List<String> list = new ArrayList<>();')
lines.append('Map<String, Integer> map = new HashMap<>();')
lines.append('```')
lines.append('')

lines.append('### 3. Functions (Methoden)')
lines.append('')
lines.append('```java')
lines.append('// Einfache Methode')
lines.append('public void sayHello() {')
lines.append('    System.out.println("Hello, Najika!");')
lines.append('}')
lines.append('')
lines.append('// Mit Parametern + Rueckgabe')
lines.append('public int addNumbers(int a, int b) {')
lines.append('    return a + b;')
lines.append('}')
lines.append('')
lines.append('// Static Methode')
lines.append('public static void main(String[] args) {')
lines.append('    System.out.println("Program started");')
lines.append('}')
lines.append('```')
lines.append('')

lines.append('### 4. Classes (Klassen)')
lines.append('')
lines.append('```java')
lines.append('public class Character {')
lines.append('    // Private Felder')
lines.append('    private String name;')
lines.append('    private int hp;')
lines.append('    ')
lines.append('    // Constructor')
lines.append('    public Character(String name, int hp) {')
lines.append('        this.name = name;')
lines.append('        this.hp = hp;')
lines.append('    }')
lines.append('    ')
lines.append('    // Getter')
lines.append('    public String getName() {')
lines.append('        return name;')
lines.append('    }')
lines.append('    ')
lines.append('    // Setter')
lines.append('    public void setHp(int hp) {')
lines.append('        this.hp = hp;')
lines.append('    }')
lines.append('    ')
lines.append('    // Methode')
lines.append('    public void takeDamage(int damage) {')
lines.append('        this.hp -= damage;')
lines.append('        System.out.println(name + " took " + damage + " damage!");')
lines.append('    }')
lines.append('    ')
lines.append('    // Berechnete Property')
lines.append('    public boolean isAlive() {')
lines.append('        return hp > 0;')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('// Nutzung')
lines.append('Character najika = new Character("Najika", 100);')
lines.append('najika.takeDamage(20);')
lines.append('```')
lines.append('')

lines.append('### 5. Control Flow')
lines.append('')
lines.append('```java')
lines.append('// If-Else')
lines.append('int hp = 75;')
lines.append('if (hp > 50) {')
lines.append('    System.out.println("Healthy");')
lines.append('} else if (hp > 20) {')
lines.append('    System.out.println("Wounded");')
lines.append('} else {')
lines.append('    System.out.println("Critical");')
lines.append('}')
lines.append('')
lines.append('// For-Loop')
lines.append('for (int i = 0; i < 10; i++) {')
lines.append('    System.out.println("Count: " + i);')
lines.append('}')
lines.append('')
lines.append('// Enhanced For-Loop')
lines.append('String[] names = {"Megumin", "Harley", "Shiro", "Melissa"};')
lines.append('for (String name : names) {')
lines.append('    System.out.println(name);')
lines.append('}')
lines.append('')
lines.append('// While-Loop')
lines.append('int count = 0;')
lines.append('while (count < 5) {')
lines.append('    System.out.println(count);')
lines.append('    count++;')
lines.append('}')
lines.append('```')
lines.append('')

lines.append('### 6. Error Handling')
lines.append('')
lines.append('```java')
lines.append('try {')
lines.append('    int result = 10 / 0;')
lines.append('} catch (ArithmeticException e) {')
lines.append('    System.out.println("Error: " + e.getMessage());')
lines.append('} catch (Exception e) {')
lines.append('    System.out.println("Unexpected error: " + e);')
lines.append('} finally {')
lines.append('    System.out.println("Cleanup");')
lines.append('}')
lines.append('```')
lines.append('')

lines.append('## Java Best Practices')
lines.append('')
lines.append('1. **Naming Conventions:**')
lines.append('   - `camelCase` fuer Variablen + Methoden')
lines.append('   - `PascalCase` fuer Klassen')
lines.append('   - `SCREAMING_SNAKE_CASE` fuer Konstanten')
lines.append('')
lines.append('2. **Encapsulation:** Felder `private`, Zugriff ueber Getter/Setter')
lines.append('')
lines.append('3. **Access Modifiers:**')
lines.append('   - `private` - Nur in der Klasse')
lines.append('   - (default) - Package-level')
lines.append('   - `protected` - Package + Subclasses')
lines.append('   - `public` - Ueberall')
lines.append('')
lines.append('4. **String Handling:**')
lines.append('   ```java')
lines.append('   // Schlecht - bei vielen Strings ineffizient')
lines.append('   String result = "";')
lines.append('   for (int i = 0; i < 1000; i++) {')
lines.append('       result += i;')
lines.append('   }')
lines.append('   ')
lines.append('   // Gut - StringBuilder nutzen')
lines.append('   StringBuilder sb = new StringBuilder();')
lines.append('   for (int i = 0; i < 1000; i++) {')
lines.append('       sb.append(i);')
lines.append('   }')
lines.append('   String result = sb.toString();')
lines.append('   ```')
lines.append('')
lines.append('5. **Exception Handling:**')
lines.append('   - Nie leere `catch` Bloecke!')
lines.append('   - Spezifische Exceptions nutzen')
lines.append('   - Ressourcen mit `try-with-resources` schliessen')
lines.append('')
lines.append('6. **SOLID Principles:**')
lines.append('   - **S**ingle Responsibility')
lines.append('   - **O**pen/Closed')
lines.append('   - **L**iskov Substitution')
lines.append('   - **I**nterface Segregation')
lines.append('   - **D**ependency Inversion')
lines.append('')

# TEIL 4: CODE-SCHREIBMETHODIK
lines.append('')
lines.append('='*80)
lines.append('# TEIL 4: CODE-SCHREIBMETHODIK')
lines.append('='*80)
lines.append('')
lines.append('## Universelle Prinzipien (fuer alle Sprachen)')
lines.append('')

lines.append('### 1. KISS - Keep It Simple, Stupid')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('def calculate(x, y, z, operation):')
lines.append('    if operation == "add":')
lines.append('        return x + y + z')
lines.append('    elif operation == "multiply":')
lines.append('        return x * y * z')
lines.append('    # ... 20 weitere elif')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('def add(x, y, z):')
lines.append('    return x + y + z')
lines.append('')
lines.append('def multiply(x, y, z):')
lines.append('    return x * y * z')
lines.append('```')
lines.append('')

lines.append('### 2. DRY - Don\'t Repeat Yourself')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('player1_hp = 100')
lines.append('player1_name = "Alice"')
lines.append('player1_score = 0')
lines.append('')
lines.append('player2_hp = 100')
lines.append('player2_name = "Bob"')
lines.append('player2_score = 0')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('class Player:')
lines.append('    def __init__(self, name):')
lines.append('        self.name = name')
lines.append('        self.hp = 100')
lines.append('        self.score = 0')
lines.append('')
lines.append('player1 = Player("Alice")')
lines.append('player2 = Player("Bob")')
lines.append('```')
lines.append('')

lines.append('### 3. YAGNI - You Ain\'t Gonna Need It')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('# Implementiere nur was du gerade brauchst')
lines.append('class Character:')
lines.append('    # ... 50 Methoden die vielleicht irgendwann benoetigt werden')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('class Character:')
lines.append('    # Nur die Methoden die JETZT gebraucht werden')
lines.append('```')
lines.append('')

lines.append('### 4. Single Responsibility Principle')
lines.append('')
lines.append('**Jede Funktion/Klasse macht NUR EINE Sache!**')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('def process_user(user_data):')
lines.append('    # Validiert Daten')
lines.append('    # Speichert in Datenbank')
lines.append('    # Sendet Email')
lines.append('    # Logged Aktivitaet')
lines.append('    # Aktualisiert Cache')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('def validate_user(user_data):')
lines.append('    # Nur Validierung')
lines.append('')
lines.append('def save_user(user_data):')
lines.append('    # Nur Speichern')
lines.append('')
lines.append('def notify_user(user):')
lines.append('    # Nur Email senden')
lines.append('```')
lines.append('')

lines.append('### 5. Naming Conventions')
lines.append('')
lines.append('**Namen sollen BESCHREIBEN was sie tun!**')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('def calc(x, y):  # Was wird berechnet?')
lines.append('    return x + y')
lines.append('')
lines.append('a = 100  # Was ist a?')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('def calculate_total_damage(base_damage, critical_multiplier):')
lines.append('    return base_damage * critical_multiplier')
lines.append('')
lines.append('player_health = 100')
lines.append('```')
lines.append('')

lines.append('### 6. Comments & Documentation')
lines.append('')
lines.append('**Code soll SELBSTERKLÄREND sein - Comments erklaeren WARUM, nicht WAS!**')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('# Addiere 1 zu x')
lines.append('x = x + 1')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('# Kompensiere Off-by-One Error in externem API')
lines.append('x = x + 1')
lines.append('```')
lines.append('')

lines.append('### 7. Error Handling')
lines.append('')
lines.append('**Behandle Fehler EXPLIZIT - keine leeren catch-Bloecke!**')
lines.append('')
lines.append('**Schlecht:**')
lines.append('```python')
lines.append('try:')
lines.append('    dangerous_operation()')
lines.append('except:')
lines.append('    pass  # Fehler wird verschluckt!')
lines.append('```')
lines.append('')
lines.append('**Gut:**')
lines.append('```python')
lines.append('try:')
lines.append('    dangerous_operation()')
lines.append('except SpecificError as e:')
lines.append('    log_error(e)')
lines.append('    notify_admin(e)')
lines.append('    return fallback_value')
lines.append('```')
lines.append('')

# TEIL 5: TRAINING CURRICULUM
lines.append('')
lines.append('='*80)
lines.append('# TEIL 5: TRAINING CURRICULUM FUER NAJIKA')
lines.append('='*80)
lines.append('')

lines.append('## Phase 1: Grundlagen (Verstehen)')
lines.append('')
lines.append('### Woche 1-2: Syntax Grundlagen')
lines.append('- [ ] Variablen in allen 3 Sprachen')
lines.append('- [ ] Datentypen verstehen')
lines.append('- [ ] Funktionen schreiben')
lines.append('- [ ] Control Flow (if/else, loops)')
lines.append('')
lines.append('**Uebungen:**')
lines.append('1. Schreibe "Hello World" in allen 3 Sprachen')
lines.append('2. Erstelle einfache Taschenrechner-Funktion')
lines.append('3. Implementiere FizzBuzz (klassisches Programmierproblem)')
lines.append('')

lines.append('### Woche 3-4: OOP Grundlagen')
lines.append('- [ ] Klassen erstellen')
lines.append('- [ ] Constructor/Destructor')
lines.append('- [ ] Methoden + Properties')
lines.append('- [ ] Encapsulation')
lines.append('')
lines.append('**Uebungen:**')
lines.append('1. Character-Klasse mit HP, Name, Damage')
lines.append('2. Inventory-System (Items hinzufuegen/entfernen)')
lines.append('3. Simple Battle-Logik (2 Charaktere kaempfen)')
lines.append('')

lines.append('## Phase 2: Anwendung (Praxis)')
lines.append('')
lines.append('### Woche 5-6: Kleine Projekte')
lines.append('- [ ] Text-basiertes RPG (Python)')
lines.append('- [ ] Simple UEFN Device (Verse)')
lines.append('- [ ] Command-line Tool (Java)')
lines.append('')

lines.append('### Woche 7-8: Code-Qualitaet')
lines.append('- [ ] Refactoring von altem Code')
lines.append('- [ ] Best Practices anwenden')
lines.append('- [ ] Error Handling implementieren')
lines.append('- [ ] Documentation schreiben')
lines.append('')

lines.append('## Phase 3: Meisterung (Expertise)')
lines.append('')
lines.append('### Woche 9-10: NajikaCore Integration')
lines.append('- [ ] Najika Server Code verstehen')
lines.append('- [ ] Neue Features implementieren')
lines.append('- [ ] Code optimieren')
lines.append('- [ ] Tests schreiben')
lines.append('')

lines.append('### Woche 11-12: Fortgeschrittene Konzepte')
lines.append('- [ ] Design Patterns')
lines.append('- [ ] Asynchronous Programming')
lines.append('- [ ] Performance Optimization')
lines.append('- [ ] Security Best Practices')
lines.append('')

# ABSCHLUSS
lines.append('')
lines.append('='*80)
lines.append('# ENDE - NAJIKA CODING TRAINING')
lines.append('='*80)
lines.append('')
lines.append('**Naechste Schritte:**')
lines.append('1. Dieses Dokument komplett lesen')
lines.append('2. Mit Phase 1 Woche 1 starten')
lines.append('3. Jeden Tag 1-2 Stunden ueben')
lines.append('4. Code schreiben, nicht nur lesen!')
lines.append('5. Fehler machen ist OK - daraus lernen!')
lines.append('')
lines.append('**Ressourcen:**')
lines.append('- Verse: dev.epicgames.com/documentation')
lines.append('- Python: docs.python.org + PEP 8')
lines.append('- Java: docs.oracle.com/javase')
lines.append('')
lines.append('**User kann Najika trainieren durch:**')
lines.append('- Code-Reviews (Najika analysiert Code)')
lines.append('- Code-Generierung (Najika schreibt Code)')
lines.append('- Fehlersuche (Najika findet Bugs)')
lines.append('- Refactoring (Najika verbessert Code)')
lines.append('')

# Speichern
OUTPUT.write_text('\n'.join(lines), encoding='utf-8')

print('\n[OK] Coding Training Dokumentation erstellt!')
print(f'  - Gespeichert: {OUTPUT}')
print(f'  - Groesse: {OUTPUT.stat().st_size:,} bytes')
print('  - Inhalte:')
print('    * Verse Programmierung (Syntax, Best Practices)')
print('    * Python Programmierung (PEP 8, Type Hints)')
print('    * Java Programmierung (OOP, SOLID)')
print('    * Code-Schreibmethodik (KISS, DRY, YAGNI)')
print('    * 12-Wochen Training Curriculum')
