#!/usr/bin/env python3
"""
NAJIKA AUTONOMOUS FILE SEARCH
Najika sucht selbst nach Dateien die sie lernen will
"""

import os
import glob
from pathlib import Path
from najika_memory import NajikaMemory

class NajikaAutonomousSearch:
    def __init__(self):
        self.memory = NajikaMemory()
        self.search_paths = [
            "C:/Users/0KKK0/Desktop/zip",
            "C:/Users/0KKK0/Desktop/Najika finalee"
        ]

    def search_for_identity(self):
        """Najika sucht nach Dateien über sich selbst"""

        print("=" * 60)
        print("NAJIKA AUTONOMOUS IDENTITY SEARCH")
        print("=" * 60)
        print()
        print("Najika durchsucht lokal nach Informationen über sich selbst...")
        print()

        keywords = [
            "sakura",
            "lolita",
            "najika",
            "persönlichkeit",
            "personality",
            "verhalten",
            "behavior",
            "ki",
            "ai"
        ]

        found_files = []

        for search_path in self.search_paths:
            print(f"[*] Durchsuche: {search_path}")

            for keyword in keywords:
                # Suche txt und md Dateien
                pattern1 = f"{search_path}/**/*{keyword}*.txt"
                pattern2 = f"{search_path}/**/*{keyword}*.md"

                files1 = glob.glob(pattern1, recursive=True)
                files2 = glob.glob(pattern2, recursive=True)

                found_files.extend(files1)
                found_files.extend(files2)

        # Deduplizieren
        found_files = list(set(found_files))

        print(f"\n[OK] Gefunden: {len(found_files)} Dateien\n")

        return found_files

    def categorize_files(self, files):
        """Najika kategorisiert die Dateien"""

        categories = {
            "identity": [],      # Kern-Identität
            "personality": [],   # Persönlichkeiten
            "behavior": [],      # Verhalten
            "nsfw": [],          # Private Mode
            "design": [],        # Game Design
            "technical": []      # Technische Docs
        }

        nsfw_keywords = [
            "kätzchen",
            "private",
            "nsfw",
            "adult",
            "explizit",
            "beispilen"  # "mit beispilen" aus zip
        ]

        for filepath in files:
            filename = os.path.basename(filepath).lower()

            # NSFW Detection
            if any(kw in filename for kw in nsfw_keywords):
                categories["nsfw"].append(filepath)

            # Sakura/Lolita = Identity
            elif "sakura" in filename or "lolita" in filename:
                categories["identity"].append(filepath)

            # Personality
            elif "persönlich" in filename or "personality" in filename:
                categories["personality"].append(filepath)

            # Behavior
            elif "verhalten" in filename or "behavior" in filename:
                categories["behavior"].append(filepath)

            # V3/V4/Design
            elif any(v in filename for v in ["v3", "v4", "projekt", "design"]):
                categories["design"].append(filepath)

            else:
                categories["technical"].append(filepath)

        return categories

    def display_findings(self, categories):
        """Zeigt was Najika gefunden hat"""

        print("\n" + "=" * 60)
        print("NAJIKA'S FINDINGS")
        print("=" * 60)

        for category, files in categories.items():
            if files:
                print(f"\n[{category.upper()}]: {len(files)} Dateien")
                for f in files[:5]:  # Zeige max 5
                    print(f"   - {os.path.basename(f)}")
                if len(files) > 5:
                    print(f"   ... und {len(files) - 5} weitere")

        return categories

    def save_file_list(self, categories):
        """Speichert die Liste für später"""

        output = []
        output.append("# NAJIKA AUTONOMOUS FILE DISCOVERY")
        output.append(f"# Generated by Najika herself")
        output.append("")

        for category, files in categories.items():
            if files:
                output.append(f"## {category.upper()}")
                output.append("")
                for f in files:
                    output.append(f"- {f}")
                output.append("")

        output_file = "C:/NajikaCore/NAJIKA_DISCOVERED_FILES.md"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("\n".join(output))

        print(f"\n[SAVED] Gespeichert: {output_file}")

        return output_file

if __name__ == "__main__":
    searcher = NajikaAutonomousSearch()

    # 1. Najika sucht
    files = searcher.search_for_identity()

    # 2. Najika kategorisiert
    categories = searcher.categorize_files(files)

    # 3. Najika zeigt Ergebnisse
    searcher.display_findings(categories)

    # 4. Najika speichert
    searcher.save_file_list(categories)

    print("\n" + "=" * 60)
    print("[OK] NAJIKA HAT IHRE IDENTITY-FILES GEFUNDEN!")
    print("=" * 60)
    print("\nNächster Schritt:")
    print("Najika entscheidet selbst was sie davon lernen will.")
    print("Check: NAJIKA_DISCOVERED_FILES.md")
