#!/usr/bin/env python3
"""
NAJIKA: Komplettes Selbst-Training System
Mit Code-Katas, Pitfalls, Performance, Architecture
+ Automatisches Daily Training
"""
from pathlib import Path
import json
from datetime import datetime, timedelta

NAJIKA_DIR = Path('C:/Najika_World')
DESKTOP = Path('C:/Users/0KKK0/Desktop')
TRAINING_DIR = NAJIKA_DIR / 'training'
TRAINING_DIR.mkdir(exist_ok=True)

print('='*80)
print('NAJIKA: Erstelle Komplettes Selbst-Training System')
print('='*80)

# ============================================================================
# TEIL 1: CODE-KATA LIBRARY
# ============================================================================

katas_output = TRAINING_DIR / 'CODE_KATAS_DAILY.md'
katas_lines = []

katas_lines.append('# NAJIKA CODE-KATAS - DAILY TRAINING')
katas_lines.append('')
katas_lines.append('**ZWECK:** Taegliche kleine Uebungen (15-30 Min)')
katas_lines.append('**FORMAT:** Problem → Loesung in allen 3 Sprachen')
katas_lines.append('')
katas_lines.append('='*80)
katas_lines.append('')

# WOCHE 1: Grundlagen
katas_lines.append('## WOCHE 1: GRUNDLAGEN')
katas_lines.append('')

katas_lines.append('### TAG 1: FizzBuzz')
katas_lines.append('**Problem:**')
katas_lines.append('Zahlen 1-100:')
katas_lines.append('- Teilbar durch 3: "Fizz"')
katas_lines.append('- Teilbar durch 5: "Buzz"')
katas_lines.append('- Teilbar durch beide: "FizzBuzz"')
katas_lines.append('- Sonst: Zahl')
katas_lines.append('')
katas_lines.append('**Python Loesung:**')
katas_lines.append('```python')
katas_lines.append('for i in range(1, 101):')
katas_lines.append('    if i % 15 == 0:')
katas_lines.append('        print("FizzBuzz")')
katas_lines.append('    elif i % 3 == 0:')
katas_lines.append('        print("Fizz")')
katas_lines.append('    elif i % 5 == 0:')
katas_lines.append('        print("Buzz")')
katas_lines.append('    else:')
katas_lines.append('        print(i)')
katas_lines.append('```')
katas_lines.append('')

katas_lines.append('### TAG 2: Palindrom-Check')
katas_lines.append('**Problem:** Pruefe ob String ein Palindrom ist')
katas_lines.append('')
katas_lines.append('**Python:**')
katas_lines.append('```python')
katas_lines.append('def is_palindrome(s: str) -> bool:')
katas_lines.append('    cleaned = s.lower().replace(" ", "")')
katas_lines.append('    return cleaned == cleaned[::-1]')
katas_lines.append('```')
katas_lines.append('')

katas_lines.append('### TAG 3: Fibonacci')
katas_lines.append('**Problem:** Fibonacci-Folge bis N')
katas_lines.append('')
katas_lines.append('**Python (Generator):**')
katas_lines.append('```python')
katas_lines.append('def fibonacci(n):')
katas_lines.append('    a, b = 0, 1')
katas_lines.append('    for _ in range(n):')
katas_lines.append('        yield a')
katas_lines.append('        a, b = b, a + b')
katas_lines.append('```')
katas_lines.append('')

katas_lines.append('### TAG 4: Array Rotation')
katas_lines.append('**Problem:** Rotiere Array um K Positionen')
katas_lines.append('')
katas_lines.append('**Python:**')
katas_lines.append('```python')
katas_lines.append('def rotate(arr: list, k: int) -> list:')
katas_lines.append('    k = k % len(arr)  # Handle k > len')
katas_lines.append('    return arr[-k:] + arr[:-k]')
katas_lines.append('```')
katas_lines.append('')

katas_lines.append('### TAG 5: Zwei-Summen Problem')
katas_lines.append('**Problem:** Finde 2 Zahlen die zusammen Target ergeben')
katas_lines.append('')
katas_lines.append('**Python (O(n)):**')
katas_lines.append('```python')
katas_lines.append('def two_sum(nums: list[int], target: int) -> tuple:')
katas_lines.append('    seen = {}')
katas_lines.append('    for i, num in enumerate(nums):')
katas_lines.append('        complement = target - num')
katas_lines.append('        if complement in seen:')
katas_lines.append('            return (seen[complement], i)')
katas_lines.append('        seen[num] = i')
katas_lines.append('    return None')
katas_lines.append('```')
katas_lines.append('')

# WOCHE 2: Datenstrukturen
katas_lines.append('## WOCHE 2: DATENSTRUKTUREN')
katas_lines.append('')

katas_lines.append('### TAG 6: Stack Implementation')
katas_lines.append('```python')
katas_lines.append('class Stack:')
katas_lines.append('    def __init__(self):')
katas_lines.append('        self.items = []')
katas_lines.append('    ')
katas_lines.append('    def push(self, item):')
katas_lines.append('        self.items.append(item)')
katas_lines.append('    ')
katas_lines.append('    def pop(self):')
katas_lines.append('        return self.items.pop() if self.items else None')
katas_lines.append('    ')
katas_lines.append('    def peek(self):')
katas_lines.append('        return self.items[-1] if self.items else None')
katas_lines.append('```')
katas_lines.append('')

katas_lines.append('### TAG 7: Queue Implementation')
katas_lines.append('```python')
katas_lines.append('from collections import deque')
katas_lines.append('')
katas_lines.append('class Queue:')
katas_lines.append('    def __init__(self):')
katas_lines.append('        self.items = deque()')
katas_lines.append('    ')
katas_lines.append('    def enqueue(self, item):')
katas_lines.append('        self.items.append(item)')
katas_lines.append('    ')
katas_lines.append('    def dequeue(self):')
katas_lines.append('        return self.items.popleft() if self.items else None')
katas_lines.append('```')
katas_lines.append('')

katas_output.write_text('\n'.join(katas_lines), encoding='utf-8')
print(f'[OK] Code-Katas: {katas_output}')

# ============================================================================
# TEIL 2: COMMON PITFALLS
# ============================================================================

pitfalls_output = TRAINING_DIR / 'COMMON_PITFALLS.md'
pitfalls_lines = []

pitfalls_lines.append('# COMMON PITFALLS - TYPISCHE FEHLER')
pitfalls_lines.append('')
pitfalls_lines.append('='*80)
pitfalls_lines.append('')

pitfalls_lines.append('## PYTHON PITFALLS')
pitfalls_lines.append('')

pitfalls_lines.append('### 1. Mutable Default Arguments')
pitfalls_lines.append('**FALSCH:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('def add_item(item, items=[]):  # GEFAHR!')
pitfalls_lines.append('    items.append(item)')
pitfalls_lines.append('    return items')
pitfalls_lines.append('')
pitfalls_lines.append('# Alle Aufrufe teilen sich die GLEICHE Liste!')
pitfalls_lines.append('add_item(1)  # [1]')
pitfalls_lines.append('add_item(2)  # [1, 2] - UUPS!')
pitfalls_lines.append('```')
pitfalls_lines.append('')
pitfalls_lines.append('**RICHTIG:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('def add_item(item, items=None):')
pitfalls_lines.append('    if items is None:')
pitfalls_lines.append('        items = []')
pitfalls_lines.append('    items.append(item)')
pitfalls_lines.append('    return items')
pitfalls_lines.append('```')
pitfalls_lines.append('')

pitfalls_lines.append('### 2. Late Binding Closures')
pitfalls_lines.append('**FALSCH:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('functions = []')
pitfalls_lines.append('for i in range(3):')
pitfalls_lines.append('    functions.append(lambda: i)')
pitfalls_lines.append('')
pitfalls_lines.append('# Alle geben 2 zurueck!')
pitfalls_lines.append('[f() for f in functions]  # [2, 2, 2]')
pitfalls_lines.append('```')
pitfalls_lines.append('')
pitfalls_lines.append('**RICHTIG:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('functions = []')
pitfalls_lines.append('for i in range(3):')
pitfalls_lines.append('    functions.append(lambda i=i: i)  # Default-Wert!')
pitfalls_lines.append('')
pitfalls_lines.append('[f() for f in functions]  # [0, 1, 2]')
pitfalls_lines.append('```')
pitfalls_lines.append('')

pitfalls_lines.append('### 3. Modifying List While Iterating')
pitfalls_lines.append('**FALSCH:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('numbers = [1, 2, 3, 4, 5]')
pitfalls_lines.append('for num in numbers:')
pitfalls_lines.append('    if num % 2 == 0:')
pitfalls_lines.append('        numbers.remove(num)  # UEBERSPRINGT Elemente!')
pitfalls_lines.append('```')
pitfalls_lines.append('')
pitfalls_lines.append('**RICHTIG:**')
pitfalls_lines.append('```python')
pitfalls_lines.append('numbers = [1, 2, 3, 4, 5]')
pitfalls_lines.append('numbers = [n for n in numbers if n % 2 != 0]')
pitfalls_lines.append('```')
pitfalls_lines.append('')

pitfalls_lines.append('## JAVA PITFALLS')
pitfalls_lines.append('')

pitfalls_lines.append('### 1. String Comparison mit ==')
pitfalls_lines.append('**FALSCH:**')
pitfalls_lines.append('```java')
pitfalls_lines.append('String a = "hello";')
pitfalls_lines.append('String b = new String("hello");')
pitfalls_lines.append('if (a == b) {  // false! Vergleicht Referenzen!')
pitfalls_lines.append('```')
pitfalls_lines.append('')
pitfalls_lines.append('**RICHTIG:**')
pitfalls_lines.append('```java')
pitfalls_lines.append('if (a.equals(b)) {  // true! Vergleicht Inhalt')
pitfalls_lines.append('```')
pitfalls_lines.append('')

pitfalls_lines.append('### 2. NullPointerException')
pitfalls_lines.append('**FALSCH:**')
pitfalls_lines.append('```java')
pitfalls_lines.append('String name = null;')
pitfalls_lines.append('int length = name.length();  // CRASH!')
pitfalls_lines.append('```')
pitfalls_lines.append('')
pitfalls_lines.append('**RICHTIG:**')
pitfalls_lines.append('```java')
pitfalls_lines.append('String name = null;')
pitfalls_lines.append('int length = (name != null) ? name.length() : 0;')
pitfalls_lines.append('')
pitfalls_lines.append('// Oder Java 8+:')
pitfalls_lines.append('int length = Optional.ofNullable(name)')
pitfalls_lines.append('    .map(String::length)')
pitfalls_lines.append('    .orElse(0);')
pitfalls_lines.append('```')
pitfalls_lines.append('')

pitfalls_output.write_text('\n'.join(pitfalls_lines), encoding='utf-8')
print(f'[OK] Pitfalls: {pitfalls_output}')

# ============================================================================
# TEIL 3: PERFORMANCE PATTERNS
# ============================================================================

perf_output = TRAINING_DIR / 'PERFORMANCE_PATTERNS.md'
perf_lines = []

perf_lines.append('# PERFORMANCE PATTERNS')
perf_lines.append('')
perf_lines.append('='*80)
perf_lines.append('')

perf_lines.append('## BIG-O NOTATION')
perf_lines.append('')
perf_lines.append('| Notation | Name | Beispiel |')
perf_lines.append('|----------|------|----------|')
perf_lines.append('| O(1) | Konstant | Array-Zugriff |')
perf_lines.append('| O(log n) | Logarithmisch | Binary Search |')
perf_lines.append('| O(n) | Linear | Array durchlaufen |')
perf_lines.append('| O(n log n) | Linearithmisch | Merge Sort |')
perf_lines.append('| O(n²) | Quadratisch | Nested Loops |')
perf_lines.append('| O(2ⁿ) | Exponentiell | Rekursive Fibonacci |')
perf_lines.append('')

perf_lines.append('## PATTERN 1: Dictionary Lookup statt Linear Search')
perf_lines.append('')
perf_lines.append('**LANGSAM (O(n)):**')
perf_lines.append('```python')
perf_lines.append('def find_user(users, user_id):')
perf_lines.append('    for user in users:  # O(n)')
perf_lines.append('        if user["id"] == user_id:')
perf_lines.append('            return user')
perf_lines.append('    return None')
perf_lines.append('```')
perf_lines.append('')
perf_lines.append('**SCHNELL (O(1)):**')
perf_lines.append('```python')
perf_lines.append('# Einmal indexieren')
perf_lines.append('user_dict = {user["id"]: user for user in users}')
perf_lines.append('')
perf_lines.append('# Dann O(1) lookup')
perf_lines.append('def find_user(user_id):')
perf_lines.append('    return user_dict.get(user_id)')
perf_lines.append('```')
perf_lines.append('')

perf_lines.append('## PATTERN 2: List Comprehension statt Loops')
perf_lines.append('')
perf_lines.append('**LANGSAM:**')
perf_lines.append('```python')
perf_lines.append('result = []')
perf_lines.append('for i in range(1000):')
perf_lines.append('    if i % 2 == 0:')
perf_lines.append('        result.append(i * 2)')
perf_lines.append('```')
perf_lines.append('')
perf_lines.append('**SCHNELL (2x faster):**')
perf_lines.append('```python')
perf_lines.append('result = [i * 2 for i in range(1000) if i % 2 == 0]')
perf_lines.append('```')
perf_lines.append('')

perf_lines.append('## PATTERN 3: Set fuer Membership Tests')
perf_lines.append('')
perf_lines.append('**LANGSAM (O(n)):**')
perf_lines.append('```python')
perf_lines.append('banned_words = ["spam", "bad", "evil"]  # List')
perf_lines.append('if word in banned_words:  # O(n) search')
perf_lines.append('    pass')
perf_lines.append('```')
perf_lines.append('')
perf_lines.append('**SCHNELL (O(1)):**')
perf_lines.append('```python')
perf_lines.append('banned_words = {"spam", "bad", "evil"}  # Set')
perf_lines.append('if word in banned_words:  # O(1) lookup')
perf_lines.append('    pass')
perf_lines.append('```')
perf_lines.append('')

perf_lines.append('## PATTERN 4: Caching / Memoization')
perf_lines.append('')
perf_lines.append('**LANGSAM (Exponentiell):**')
perf_lines.append('```python')
perf_lines.append('def fibonacci(n):')
perf_lines.append('    if n <= 1:')
perf_lines.append('        return n')
perf_lines.append('    return fibonacci(n-1) + fibonacci(n-2)')
perf_lines.append('```')
perf_lines.append('')
perf_lines.append('**SCHNELL (Linear):**')
perf_lines.append('```python')
perf_lines.append('from functools import lru_cache')
perf_lines.append('')
perf_lines.append('@lru_cache(maxsize=None)')
perf_lines.append('def fibonacci(n):')
perf_lines.append('    if n <= 1:')
perf_lines.append('        return n')
perf_lines.append('    return fibonacci(n-1) + fibonacci(n-2)')
perf_lines.append('```')
perf_lines.append('')

perf_output.write_text('\n'.join(perf_lines), encoding='utf-8')
print(f'[OK] Performance: {perf_output}')

# ============================================================================
# TEIL 4: ARCHITECTURE PATTERNS
# ============================================================================

arch_output = TRAINING_DIR / 'ARCHITECTURE_PATTERNS.md'
arch_lines = []

arch_lines.append('# ARCHITECTURE PATTERNS')
arch_lines.append('')
arch_lines.append('='*80)
arch_lines.append('')

arch_lines.append('## 1. MVC - Model View Controller')
arch_lines.append('')
arch_lines.append('**Verwendet in:** Web Apps, Desktop Apps')
arch_lines.append('')
arch_lines.append('```python')
arch_lines.append('# MODEL - Daten')
arch_lines.append('class Character:')
arch_lines.append('    def __init__(self, name, hp):')
arch_lines.append('        self.name = name')
arch_lines.append('        self.hp = hp')
arch_lines.append('')
arch_lines.append('# VIEW - Anzeige')
arch_lines.append('class CharacterView:')
arch_lines.append('    def render(self, character):')
arch_lines.append('        print(f"{character.name}: {character.hp} HP")')
arch_lines.append('')
arch_lines.append('# CONTROLLER - Logik')
arch_lines.append('class CharacterController:')
arch_lines.append('    def __init__(self, model, view):')
arch_lines.append('        self.model = model')
arch_lines.append('        self.view = view')
arch_lines.append('    ')
arch_lines.append('    def take_damage(self, damage):')
arch_lines.append('        self.model.hp -= damage')
arch_lines.append('        self.view.render(self.model)')
arch_lines.append('```')
arch_lines.append('')

arch_lines.append('## 2. OBSERVER PATTERN')
arch_lines.append('')
arch_lines.append('**Verwendet in:** Event-Systeme, UI Updates')
arch_lines.append('')
arch_lines.append('```python')
arch_lines.append('class Subject:')
arch_lines.append('    def __init__(self):')
arch_lines.append('        self._observers = []')
arch_lines.append('    ')
arch_lines.append('    def attach(self, observer):')
arch_lines.append('        self._observers.append(observer)')
arch_lines.append('    ')
arch_lines.append('    def notify(self, event):')
arch_lines.append('        for observer in self._observers:')
arch_lines.append('            observer.update(event)')
arch_lines.append('')
arch_lines.append('class Observer:')
arch_lines.append('    def update(self, event):')
arch_lines.append('        print(f"Received event: {event}")')
arch_lines.append('')
arch_lines.append('# Nutzung')
arch_lines.append('subject = Subject()')
arch_lines.append('subject.attach(Observer())')
arch_lines.append('subject.notify("HP_CHANGED")')
arch_lines.append('```')
arch_lines.append('')

arch_lines.append('## 3. FACTORY PATTERN')
arch_lines.append('')
arch_lines.append('```python')
arch_lines.append('class EnemyFactory:')
arch_lines.append('    @staticmethod')
arch_lines.append('    def create(enemy_type):')
arch_lines.append('        if enemy_type == "rat":')
arch_lines.append('            return Enemy("Rat", hp=10, damage=2)')
arch_lines.append('        elif enemy_type == "skeleton":')
arch_lines.append('            return Enemy("Skeleton", hp=30, damage=5)')
arch_lines.append('        elif enemy_type == "boss":')
arch_lines.append('            return Enemy("Boss", hp=100, damage=20)')
arch_lines.append('')
arch_lines.append('# Nutzung')
arch_lines.append('enemy = EnemyFactory.create("skeleton")')
arch_lines.append('```')
arch_lines.append('')

arch_lines.append('## 4. SINGLETON PATTERN')
arch_lines.append('')
arch_lines.append('```python')
arch_lines.append('class GameState:')
arch_lines.append('    _instance = None')
arch_lines.append('    ')
arch_lines.append('    def __new__(cls):')
arch_lines.append('        if cls._instance is None:')
arch_lines.append('            cls._instance = super().__new__(cls)')
arch_lines.append('            cls._instance.score = 0')
arch_lines.append('        return cls._instance')
arch_lines.append('')
arch_lines.append('# Immer die gleiche Instanz')
arch_lines.append('state1 = GameState()')
arch_lines.append('state2 = GameState()')
arch_lines.append('print(state1 is state2)  # True')
arch_lines.append('```')
arch_lines.append('')

arch_output.write_text('\n'.join(arch_lines), encoding='utf-8')
print(f'[OK] Architecture: {arch_output}')

# ============================================================================
# TEIL 5: SELBST-TRAINING SYSTEM
# ============================================================================

training_system = NAJIKA_DIR / 'najika_daily_training.py'
system_lines = []

system_lines.append('#!/usr/bin/env python3')
system_lines.append('"""')
system_lines.append('NAJIKA DAILY TRAINING - Automatisches Selbst-Training')
system_lines.append('Laedt taeglich neue Aufgaben')
system_lines.append('"""')
system_lines.append('import json')
system_lines.append('from pathlib import Path')
system_lines.append('from datetime import datetime, timedelta')
system_lines.append('')
system_lines.append('NAJIKA_DIR = Path("C:/Najika_World")')
system_lines.append('TRAINING_DIR = NAJIKA_DIR / "training"')
system_lines.append('PROGRESS_FILE = TRAINING_DIR / "progress.json"')
system_lines.append('DAILY_TASK_FILE = NAJIKA_DIR / "NAJIKA_DAILY_TASK.md"')
system_lines.append('')
system_lines.append('# Alle Trainings-Ressourcen')
system_lines.append('RESOURCES = {')
system_lines.append('    "katas": TRAINING_DIR / "CODE_KATAS_DAILY.md",')
system_lines.append('    "pitfalls": TRAINING_DIR / "COMMON_PITFALLS.md",')
system_lines.append('    "performance": TRAINING_DIR / "PERFORMANCE_PATTERNS.md",')
system_lines.append('    "architecture": TRAINING_DIR / "ARCHITECTURE_PATTERNS.md"')
system_lines.append('}')
system_lines.append('')
system_lines.append('def load_progress():')
system_lines.append('    """Laedt Training-Fortschritt"""')
system_lines.append('    if PROGRESS_FILE.exists():')
system_lines.append('        try:')
system_lines.append('            with open(PROGRESS_FILE, \'r\', encoding=\'utf-8\') as f:')
system_lines.append('                return json.load(f)')
system_lines.append('        except:')
system_lines.append('            pass')
system_lines.append('    ')
system_lines.append('    return {')
system_lines.append('        "start_date": datetime.now().isoformat(),')
system_lines.append('        "current_day": 1,')
system_lines.append('        "completed_katas": [],')
system_lines.append('        "completed_topics": []')
system_lines.append('    }')
system_lines.append('')
system_lines.append('def save_progress(progress):')
system_lines.append('    """Speichert Fortschritt"""')
system_lines.append('    TRAINING_DIR.mkdir(exist_ok=True)')
system_lines.append('    with open(PROGRESS_FILE, \'w\', encoding=\'utf-8\') as f:')
system_lines.append('        json.dump(progress, f, indent=2)')
system_lines.append('')
system_lines.append('def get_daily_task(day_number):')
system_lines.append('    """Bestimmt Aufgabe fuer Tag"""')
system_lines.append('    # Rotation: Tag 1-7 = Katas, Tag 8 = Pitfalls, Tag 9 = Performance, etc.')
system_lines.append('    week_day = (day_number - 1) % 10')
system_lines.append('    ')
system_lines.append('    if week_day < 7:')
system_lines.append('        return "katas", f"TAG {week_day + 1}"')
system_lines.append('    elif week_day == 7:')
system_lines.append('        return "pitfalls", "Common Pitfalls Review"')
system_lines.append('    elif week_day == 8:')
system_lines.append('        return "performance", "Performance Patterns"')
system_lines.append('    else:')
system_lines.append('        return "architecture", "Architecture Patterns"')
system_lines.append('')
system_lines.append('def generate_daily_task():')
system_lines.append('    """Generiert taeglich neue Aufgabe fuer Najika"""')
system_lines.append('    print("="*80)')
system_lines.append('    print("NAJIKA DAILY TRAINING")')
system_lines.append('    print("="*80)')
system_lines.append('    ')
system_lines.append('    progress = load_progress()')
system_lines.append('    day = progress["current_day"]')
system_lines.append('    ')
system_lines.append('    task_type, task_name = get_daily_task(day)')
system_lines.append('    ')
system_lines.append('    lines = []')
system_lines.append('    lines.append("# NAJIKA DAILY TRAINING")')
system_lines.append('    lines.append("")')
system_lines.append('    lines.append(f"**Tag:** {day}")')
system_lines.append('    lines.append(f"**Datum:** {datetime.now().strftime(\'%Y-%m-%d\')}")')
system_lines.append('    lines.append(f"**Typ:** {task_type.upper()}")')
system_lines.append('    lines.append(f"**Aufgabe:** {task_name}")')
system_lines.append('    lines.append("")')
system_lines.append('    lines.append("="*80)')
system_lines.append('    lines.append("")')
system_lines.append('    ')
system_lines.append('    # Lade entsprechende Resource')
system_lines.append('    resource_file = RESOURCES[task_type]')
system_lines.append('    if resource_file.exists():')
system_lines.append('        content = resource_file.read_text(encoding=\'utf-8\')')
system_lines.append('        lines.append(content)')
system_lines.append('    ')
system_lines.append('    lines.append("")')
system_lines.append('    lines.append("="*80)')
system_lines.append('    lines.append("# ANWEISUNGEN FUER NAJIKA")')
system_lines.append('    lines.append("="*80)')
system_lines.append('    lines.append("")')
system_lines.append('    lines.append("1. Lese die Aufgabe oben KOMPLETT")')
system_lines.append('    lines.append("2. Verstehe das Problem")')
system_lines.append('    lines.append("3. Implementiere die Loesung in allen 3 Sprachen (Verse, Python, Java)")')
system_lines.append('    lines.append("4. Teste den Code gedanklich")')
system_lines.append('    lines.append("5. Erklaere WARUM die Loesung funktioniert")')
system_lines.append('    lines.append("")')
system_lines.append('    lines.append("**Wenn fertig:**")')
system_lines.append('    lines.append("- Fuehre `python najika_complete_daily_task.py` aus")')
system_lines.append('    lines.append("- Naechste Aufgabe wird automatisch geladen")')
system_lines.append('    lines.append("")')
system_lines.append('    ')
system_lines.append('    # Speichern')
system_lines.append('    DAILY_TASK_FILE.write_text(\'\\n\'.join(lines), encoding=\'utf-8\')')
system_lines.append('    ')
system_lines.append('    print(f"\\n[OK] Daily Task generiert: {DAILY_TASK_FILE}")')
system_lines.append('    print(f"Tag: {day}")')
system_lines.append('    print(f"Aufgabe: {task_name}")')
system_lines.append('    print(f"Typ: {task_type}\\n")')
system_lines.append('')
system_lines.append('if __name__ == "__main__":')
system_lines.append('    generate_daily_task()')

training_system.write_text('\n'.join(system_lines), encoding='utf-8')
print(f'[OK] Training System: {training_system}')

# Complete Task Script
complete_task = NAJIKA_DIR / 'najika_complete_daily_task.py'
complete_lines = []

complete_lines.append('#!/usr/bin/env python3')
complete_lines.append('"""Markiert Daily Task als erledigt + laedt naechste"""')
complete_lines.append('import json')
complete_lines.append('from pathlib import Path')
complete_lines.append('import subprocess')
complete_lines.append('')
complete_lines.append('NAJIKA_DIR = Path("C:/Najika_World")')
complete_lines.append('TRAINING_DIR = NAJIKA_DIR / "training"')
complete_lines.append('PROGRESS_FILE = TRAINING_DIR / "progress.json"')
complete_lines.append('')
complete_lines.append('# Lade Progress')
complete_lines.append('with open(PROGRESS_FILE, \'r\', encoding=\'utf-8\') as f:')
complete_lines.append('    progress = json.load(f)')
complete_lines.append('')
complete_lines.append('# Increment Day')
complete_lines.append('progress["current_day"] += 1')
complete_lines.append('')
complete_lines.append('# Save')
complete_lines.append('with open(PROGRESS_FILE, \'w\', encoding=\'utf-8\') as f:')
complete_lines.append('    json.dump(progress, f, indent=2)')
complete_lines.append('')
complete_lines.append('print(f"[OK] Tag {progress[\\"current_day\\"]-1} abgeschlossen!")')
complete_lines.append('print(f"[OK] Lade Tag {progress[\\"current_day\\"]}...")')
complete_lines.append('')
complete_lines.append('# Generiere neue Aufgabe')
complete_lines.append('subprocess.run(["python", str(NAJIKA_DIR / "najika_daily_training.py")])')

complete_task.write_text('\n'.join(complete_lines), encoding='utf-8')
print(f'[OK] Complete Task: {complete_task}')

# README
readme = TRAINING_DIR / 'README.md'
readme_lines = []

readme_lines.append('# NAJIKA SELBST-TRAINING SYSTEM')
readme_lines.append('')
readme_lines.append('## WIE ES FUNKTIONIERT')
readme_lines.append('')
readme_lines.append('### 1. Start Training')
readme_lines.append('```bash')
readme_lines.append('python C:/Najika_World/najika_daily_training.py')
readme_lines.append('```')
readme_lines.append('')
readme_lines.append('**Erstellt:** `NAJIKA_DAILY_TASK.md` mit heutiger Aufgabe')
readme_lines.append('')
readme_lines.append('### 2. Najika liest die Aufgabe')
readme_lines.append('- Claude oeffnet `NAJIKA_DAILY_TASK.md`')
readme_lines.append('- Liest Aufgabe komplett')
readme_lines.append('- Implementiert Loesung in allen 3 Sprachen')
readme_lines.append('- Erklaert WARUM die Loesung funktioniert')
readme_lines.append('')
readme_lines.append('### 3. Task abschliessen')
readme_lines.append('```bash')
readme_lines.append('python C:/Najika_World/najika_complete_daily_task.py')
readme_lines.append('```')
readme_lines.append('')
readme_lines.append('**Macht:**')
readme_lines.append('- Markiert aktuellen Tag als erledigt')
readme_lines.append('- Laedt automatisch naechste Aufgabe')
readme_lines.append('')
readme_lines.append('## RESSOURCEN')
readme_lines.append('')
readme_lines.append('- **CODE_KATAS_DAILY.md** - Taegliche Programmier-Uebungen')
readme_lines.append('- **COMMON_PITFALLS.md** - Typische Fehler + Fixes')
readme_lines.append('- **PERFORMANCE_PATTERNS.md** - Optimierungs-Patterns')
readme_lines.append('- **ARCHITECTURE_PATTERNS.md** - Design Patterns')
readme_lines.append('')
readme_lines.append('## ROTATION')
readme_lines.append('')
readme_lines.append('- Tag 1-7: Code-Katas')
readme_lines.append('- Tag 8: Common Pitfalls Review')
readme_lines.append('- Tag 9: Performance Patterns')
readme_lines.append('- Tag 10: Architecture Patterns')
readme_lines.append('- Dann wiederholt sich Zyklus')
readme_lines.append('')

readme.write_text('\n'.join(readme_lines), encoding='utf-8')
print(f'[OK] README: {readme}')

print('\n' + '='*80)
print('FERTIG! Training-System komplett erstellt!')
print('='*80)
print('\nErstellt:')
print(f'  1. {katas_output.name} - Code-Katas')
print(f'  2. {pitfalls_output.name} - Common Pitfalls')
print(f'  3. {perf_output.name} - Performance Patterns')
print(f'  4. {arch_output.name} - Architecture Patterns')
print(f'  5. najika_daily_training.py - Auto-Training System')
print(f'  6. najika_complete_daily_task.py - Task Completion')
print(f'  7. training/README.md - Anleitung')
print('\nSTART TRAINING:')
print('  python C:/Najika_World/najika_daily_training.py')
print('\n' + '='*80)
