#!/usr/bin/env python3
# =============================================================================
# SETUP SCRIPT - Code Models für Najika
# =============================================================================
# Installiert StarCoder2 und konfiguriert Claude API
#
# Ausführen: python setup_code_models.py
# =============================================================================

import subprocess
import os
import sys
import json

def get_system_info():
    """Sammelt System-Informationen"""
    info = {
        "os": sys.platform,
        "python": sys.version,
        "vram_gb": 8,  # Default
        "is_jetson": False
    }

    # Jetson Detection
    if os.path.exists("/etc/nv_tegra_release"):
        info["is_jetson"] = True
        info["vram_gb"] = 64  # Orin 64GB

    # VRAM Detection via PyTorch
    try:
        import torch
        if torch.cuda.is_available():
            props = torch.cuda.get_device_properties(0)
            info["vram_gb"] = props.total_memory // (1024**3)
            info["gpu_name"] = props.name
    except:
        pass

    return info

def check_ollama():
    """Prüft ob Ollama installiert ist"""
    try:
        result = subprocess.run(["ollama", "--version"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False

def install_ollama():
    """Installiert Ollama"""
    print("\n[SETUP] Ollama nicht gefunden. Installation...")

    if sys.platform == "win32":
        print("Bitte Ollama manuell installieren: https://ollama.com/download")
        return False
    else:
        # Linux/Mac
        try:
            subprocess.run(
                "curl -fsSL https://ollama.com/install.sh | sh",
                shell=True,
                check=True
            )
            return True
        except:
            print("Ollama Installation fehlgeschlagen!")
            return False

def list_ollama_models():
    """Listet installierte Ollama-Modelle"""
    try:
        result = subprocess.run(["ollama", "list"], capture_output=True, text=True)
        return result.stdout
    except:
        return ""

def pull_model(model_name: str, timeout: int = 1800):
    """Zieht ein Ollama-Modell"""
    print(f"\n[SETUP] Installiere {model_name}...")
    print("Dies kann einige Minuten dauern...")

    try:
        process = subprocess.Popen(
            ["ollama", "pull", model_name],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

        for line in process.stdout:
            print(line, end="")

        process.wait(timeout=timeout)
        return process.returncode == 0

    except subprocess.TimeoutExpired:
        process.kill()
        print(f"[SETUP] Timeout bei {model_name}")
        return False
    except Exception as e:
        print(f"[SETUP] Fehler: {e}")
        return False

def setup_env_file():
    """Erstellt/aktualisiert .env Datei für API Keys"""
    env_path = os.path.join(os.path.dirname(__file__), ".env")

    env_vars = {}

    # Existierende .env laden
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    env_vars[key] = value

    # Anthropic API Key abfragen wenn nicht vorhanden
    if "ANTHROPIC_API_KEY" not in env_vars or not env_vars["ANTHROPIC_API_KEY"]:
        print("\n" + "=" * 60)
        print("CLAUDE API SETUP")
        print("=" * 60)
        print("Für beste Code-Qualität wird Claude Sonnet als Fallback empfohlen.")
        print("API Key erhältlich unter: https://console.anthropic.com/")
        print("")
        api_key = input("Anthropic API Key eingeben (oder Enter zum Überspringen): ").strip()

        if api_key:
            env_vars["ANTHROPIC_API_KEY"] = api_key
            print("[SETUP] API Key gespeichert!")
        else:
            print("[SETUP] Kein API Key - Claude Fallback deaktiviert")
            env_vars["ANTHROPIC_API_KEY"] = ""

    # .env schreiben
    with open(env_path, "w") as f:
        f.write("# Najika Environment Variables\n")
        f.write("# Auto-generated by setup_code_models.py\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")

    print(f"[SETUP] .env aktualisiert: {env_path}")

def create_najika_wizard():
    """Erstellt najika-wizard Modell für Kätzchen-Modus (NSFW)"""
    modelfile_path = os.path.join(os.path.dirname(__file__), "najika_wizard_QWEN.Modelfile")

    if not os.path.exists(modelfile_path):
        print(f"[SETUP] Modelfile nicht gefunden: {modelfile_path}")
        return False

    print("\n[SETUP] Erstelle najika-wizard Modell für Kätzchen-Modus...")
    print("  Basis: qwen2.5:7b-instruct")
    print("  Zweck: NSFW-Content ohne Filter")

    try:
        process = subprocess.Popen(
            ["ollama", "create", "najika-wizard", "-f", modelfile_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

        for line in process.stdout:
            print(f"  {line}", end="")

        process.wait(timeout=600)
        return process.returncode == 0

    except Exception as e:
        print(f"[SETUP] Fehler beim Erstellen: {e}")
        return False


def main():
    print("=" * 60)
    print("NAJIKA CODE MODELS SETUP")
    print("=" * 60)

    # System Info
    info = get_system_info()
    print(f"\n[SYSTEM]")
    print(f"  OS: {info['os']}")
    print(f"  Python: {info['python'].split()[0]}")
    print(f"  GPU VRAM: {info['vram_gb']} GB")
    print(f"  Jetson: {'Ja' if info['is_jetson'] else 'Nein'}")

    # Ollama Check
    if not check_ollama():
        if not install_ollama():
            print("\n[ERROR] Ollama benötigt! Bitte manuell installieren.")
            sys.exit(1)

    print("\n[OLLAMA] Installiert und bereit")

    # Aktuell installierte Modelle
    print("\n[MODELLE] Aktuell installiert:")
    print(list_ollama_models())

    # Modelle basierend auf VRAM auswählen
    models_to_install = []

    if info["vram_gb"] >= 48:
        # Jetson Orin 64GB oder High-End GPU
        print("\n[HARDWARE] High-End erkannt - installiere große Modelle")
        models_to_install = [
            "starcoder2:15b",  # 15B - beste Qualität
            "starcoder2:7b",   # 7B - Backup
            "qwen2.5-coder:7b" # Qwen Code Variante
        ]
    elif info["vram_gb"] >= 16:
        print("\n[HARDWARE] Mid-Range erkannt - installiere mittlere Modelle")
        models_to_install = [
            "starcoder2:7b",
            "starcoder2:3b"
        ]
    else:
        # RTX 3060 Ti (8GB) oder weniger
        print("\n[HARDWARE] Standard-GPU erkannt - installiere kleine Modelle")
        models_to_install = [
            "starcoder2:3b"
        ]

    # User Confirmation
    print(f"\n[PLAN] Folgende Modelle werden installiert:")
    for m in models_to_install:
        print(f"  - {m}")

    confirm = input("\nFortfahren? (j/n): ").strip().lower()
    if confirm != "j":
        print("Abgebrochen.")
        sys.exit(0)

    # Modelle installieren
    results = {}
    for model in models_to_install:
        results[model] = pull_model(model)

    # Ergebnis anzeigen
    print("\n" + "=" * 60)
    print("INSTALLATION ABGESCHLOSSEN")
    print("=" * 60)
    for model, success in results.items():
        status = "[OK]" if success else "[FAILED]"
        print(f"  {status} {model}")

    # Claude API Setup
    setup_env_file()

    # Najika-Wizard für Kätzchen-Modus
    print("\n" + "=" * 60)
    print("KÄTZCHEN-MODUS SETUP (NSFW)")
    print("=" * 60)

    # Check ob najika-wizard existiert
    models = list_ollama_models()
    if "najika-wizard" not in models:
        create_wizard = input("\nnajika-wizard nicht gefunden. Für Kätzchen-Modus erstellen? (j/n): ").strip().lower()
        if create_wizard == "j":
            create_najika_wizard()
    else:
        print("[OK] najika-wizard bereits vorhanden")

    # Test
    print("\n[TEST] Code Engine testen...")
    try:
        from najika_code_engine import init_code_engine
        engine = init_code_engine()
        print(f"  Primary Model: {engine.primary_model.value}")
        print(f"  Claude API: {'Verfügbar' if engine.claude_client else 'Nicht konfiguriert'}")

        # Kurzer Test
        result = engine.generate_code("def hello(): return 'Hello World'")
        if "ERROR" not in result["response"]:
            print("  Test: PASSED!")
        else:
            print(f"  Test: FAILED - {result['response'][:100]}")

    except Exception as e:
        print(f"  Test: ERROR - {e}")

    print("\n[FERTIG] Setup abgeschlossen!")
    print("Starte den Server mit: python najika_server.py")


if __name__ == "__main__":
    main()
