"""Add PHASE 3 models - instrument, oregon trail, boss spawns, world state, voice, multiplayer

Revision ID: dc02ab76c2db
Revises: ed9761623b76
Create Date: 2025-11-18 11:14:32.758925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc02ab76c2db'
down_revision = 'ed9761623b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_spawns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('boss_name', sa.String(length=200), nullable=False),
    sa.Column('boss_type', sa.String(length=50), nullable=False),
    sa.Column('boss_level', sa.Integer(), nullable=False),
    sa.Column('boss_health', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('defeated', sa.Boolean(), nullable=True),
    sa.Column('spawn_location', sa.String(length=200), nullable=False),
    sa.Column('spawn_radius', sa.Integer(), nullable=True),
    sa.Column('guaranteed_drops', sa.JSON(), nullable=True),
    sa.Column('rare_drops', sa.JSON(), nullable=True),
    sa.Column('gold_reward', sa.Integer(), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('phases', sa.Integer(), nullable=True),
    sa.Column('enrage_timer', sa.Integer(), nullable=True),
    sa.Column('recommended_players', sa.Integer(), nullable=True),
    sa.Column('recommended_level', sa.Integer(), nullable=True),
    sa.Column('respawn_time_hours', sa.Integer(), nullable=True),
    sa.Column('last_defeated_at', sa.DateTime(), nullable=True),
    sa.Column('next_spawn_at', sa.DateTime(), nullable=True),
    sa.Column('spawned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boss_spawns_id'), 'boss_spawns', ['id'], unique=False)
    op.create_index(op.f('ix_boss_spawns_region_name'), 'boss_spawns', ['region_name'], unique=False)
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_time', sa.Integer(), nullable=True),
    sa.Column('world_day', sa.Integer(), nullable=True),
    sa.Column('world_season', sa.String(length=20), nullable=True),
    sa.Column('current_weather', sa.String(length=50), nullable=True),
    sa.Column('active_events', sa.JSON(), nullable=True),
    sa.Column('event_flags', sa.JSON(), nullable=True),
    sa.Column('world_boss_spawned', sa.Boolean(), nullable=True),
    sa.Column('world_boss_name', sa.String(length=200), nullable=True),
    sa.Column('world_boss_location', sa.String(length=200), nullable=True),
    sa.Column('global_gold_pool', sa.Integer(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('server_version', sa.String(length=50), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_state_id'), 'world_state', ['id'], unique=False)
    op.create_table('boss_spawn_defeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('party_members', sa.JSON(), nullable=True),
    sa.Column('time_to_kill', sa.Integer(), nullable=False),
    sa.Column('deaths_during_fight', sa.Integer(), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('damage_taken', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('exp_earned', sa.Integer(), nullable=True),
    sa.Column('items_dropped', sa.JSON(), nullable=True),
    sa.Column('first_kill', sa.Boolean(), nullable=True),
    sa.Column('flawless', sa.Boolean(), nullable=True),
    sa.Column('speedrun', sa.Boolean(), nullable=True),
    sa.Column('defeated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['boss_spawns.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boss_spawn_defeats_id'), 'boss_spawn_defeats', ['id'], unique=False)
    op.create_table('instrument_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('current_instrument', sa.String(length=50), nullable=True),
    sa.Column('instrument_skills', sa.JSON(), nullable=True),
    sa.Column('instrument_experience', sa.JSON(), nullable=True),
    sa.Column('learned_songs', sa.JSON(), nullable=True),
    sa.Column('total_notes_played', sa.Integer(), nullable=True),
    sa.Column('perfect_notes', sa.Integer(), nullable=True),
    sa.Column('great_notes', sa.Integer(), nullable=True),
    sa.Column('good_notes', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_progress_id'), 'instrument_progress', ['id'], unique=False)
    op.create_table('learned_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(length=100), nullable=False),
    sa.Column('song_name', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('times_played', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_songs_id'), 'learned_songs', ['id'], unique=False)
    op.create_table('multiplayer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=200), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('ended', sa.Boolean(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('password_protected', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('game_mode', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('current_region', sa.String(length=100), nullable=True),
    sa.Column('current_activity', sa.String(length=100), nullable=True),
    sa.Column('objectives_completed', sa.Integer(), nullable=True),
    sa.Column('total_objectives', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_code')
    )
    op.create_index(op.f('ix_multiplayer_sessions_id'), 'multiplayer_sessions', ['id'], unique=False)
    op.create_table('oregon_trail_journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('distance_traveled', sa.Integer(), nullable=True),
    sa.Column('days_elapsed', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('party_health', sa.Float(), nullable=True),
    sa.Column('party_morale', sa.Float(), nullable=True),
    sa.Column('party_members', sa.JSON(), nullable=True),
    sa.Column('alive_members', sa.Integer(), nullable=True),
    sa.Column('food', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('ammunition', sa.Integer(), nullable=True),
    sa.Column('oxen', sa.Integer(), nullable=True),
    sa.Column('wagon_wheels', sa.Integer(), nullable=True),
    sa.Column('wagon_axles', sa.Integer(), nullable=True),
    sa.Column('wagon_tongues', sa.Integer(), nullable=True),
    sa.Column('current_weather', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('pace', sa.String(length=20), nullable=True),
    sa.Column('rations', sa.String(length=20), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oregon_trail_journeys_id'), 'oregon_trail_journeys', ['id'], unique=False)
    op.create_table('player_world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('current_region', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('discovered_regions', sa.JSON(), nullable=True),
    sa.Column('unlocked_teleports', sa.JSON(), nullable=True),
    sa.Column('completed_quests', sa.JSON(), nullable=True),
    sa.Column('active_quests', sa.JSON(), nullable=True),
    sa.Column('quest_progress', sa.JSON(), nullable=True),
    sa.Column('found_treasures', sa.JSON(), nullable=True),
    sa.Column('collected_artifacts', sa.JSON(), nullable=True),
    sa.Column('faction_reputation', sa.JSON(), nullable=True),
    sa.Column('last_position_update', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_player_world_state_id'), 'player_world_state', ['id'], unique=False)
    op.create_table('voice_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('ended', sa.Boolean(), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_quality', sa.String(length=20), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('words_spoken', sa.Integer(), nullable=True),
    sa.Column('cost_credits', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_id'), 'voice_calls', ['id'], unique=False)
    op.create_table('voice_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tts_voice', sa.String(length=50), nullable=True),
    sa.Column('tts_speed', sa.Float(), nullable=True),
    sa.Column('tts_pitch', sa.Float(), nullable=True),
    sa.Column('tts_volume', sa.Float(), nullable=True),
    sa.Column('stt_language', sa.String(length=10), nullable=True),
    sa.Column('stt_auto_detect', sa.Boolean(), nullable=True),
    sa.Column('voice_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_play_response', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_voice_settings_id'), 'voice_settings', ['id'], unique=False)
    op.create_table('oregon_trail_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('player_choice', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=True),
    sa.Column('location_at_event', sa.String(length=100), nullable=False),
    sa.Column('distance_at_event', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['oregon_trail_journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oregon_trail_events_id'), 'oregon_trail_events', ['id'], unique=False)
    op.create_table('played_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=3), nullable=False),
    sa.Column('octave', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['progress_id'], ['instrument_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_played_notes_id'), 'played_notes', ['id'], unique=False)
    op.create_table('session_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('healing_done', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('connection_quality', sa.String(length=20), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['multiplayer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_id'), 'session_participants', ['id'], unique=False)
    op.create_table('voice_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('ai_response_audio', sa.String(length=500), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['voice_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_messages_id'), 'voice_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_messages_id'), table_name='voice_messages')
    op.drop_table('voice_messages')
    op.drop_index(op.f('ix_session_participants_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_played_notes_id'), table_name='played_notes')
    op.drop_table('played_notes')
    op.drop_index(op.f('ix_oregon_trail_events_id'), table_name='oregon_trail_events')
    op.drop_table('oregon_trail_events')
    op.drop_index(op.f('ix_voice_settings_id'), table_name='voice_settings')
    op.drop_table('voice_settings')
    op.drop_index(op.f('ix_voice_calls_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_index(op.f('ix_player_world_state_id'), table_name='player_world_state')
    op.drop_table('player_world_state')
    op.drop_index(op.f('ix_oregon_trail_journeys_id'), table_name='oregon_trail_journeys')
    op.drop_table('oregon_trail_journeys')
    op.drop_index(op.f('ix_multiplayer_sessions_id'), table_name='multiplayer_sessions')
    op.drop_table('multiplayer_sessions')
    op.drop_index(op.f('ix_learned_songs_id'), table_name='learned_songs')
    op.drop_table('learned_songs')
    op.drop_index(op.f('ix_instrument_progress_id'), table_name='instrument_progress')
    op.drop_table('instrument_progress')
    op.drop_index(op.f('ix_boss_spawn_defeats_id'), table_name='boss_spawn_defeats')
    op.drop_table('boss_spawn_defeats')
    op.drop_index(op.f('ix_world_state_id'), table_name='world_state')
    op.drop_table('world_state')
    op.drop_index(op.f('ix_boss_spawns_region_name'), table_name='boss_spawns')
    op.drop_index(op.f('ix_boss_spawns_id'), table_name='boss_spawns')
    op.drop_table('boss_spawns')
    # ### end Alembic commands ###
