"""add_world_map_system

Revision ID: f378e4d689d4
Revises: d41dc786d814
Create Date: 2025-11-18 22:45:13.220723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f378e4d689d4'
down_revision = 'd41dc786d814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_night_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_hour', sa.Float(), nullable=True),
    sa.Column('current_day', sa.Integer(), nullable=True),
    sa.Column('time_scale', sa.Float(), nullable=True),
    sa.Column('sun_angle', sa.Float(), nullable=True),
    sa.Column('moon_phase', sa.Float(), nullable=True),
    sa.Column('ambient_light', sa.Float(), nullable=True),
    sa.Column('sun_intensity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_night_cycle_id'), 'day_night_cycle', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('biome_type', sa.String(length=50), nullable=True),
    sa.Column('slime_color', sa.String(length=50), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('terrain_config', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('dangers', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('fast_travel_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('point_type', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('unlock_requirement', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fast_travel_points_id'), 'fast_travel_points', ['id'], unique=False)
    op.create_table('player_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('world_x', sa.Float(), nullable=True),
    sa.Column('world_y', sa.Float(), nullable=True),
    sa.Column('world_z', sa.Float(), nullable=True),
    sa.Column('rotation_y', sa.Float(), nullable=True),
    sa.Column('is_in_house', sa.Boolean(), nullable=True),
    sa.Column('is_in_dungeon', sa.Boolean(), nullable=True),
    sa.Column('current_room', sa.String(length=50), nullable=True),
    sa.Column('last_moved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_player_positions_id'), 'player_positions', ['id'], unique=False)
    op.create_table('region_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_a_id', sa.Integer(), nullable=True),
    sa.Column('region_b_id', sa.Integer(), nullable=True),
    sa.Column('start_x', sa.Float(), nullable=True),
    sa.Column('start_y', sa.Float(), nullable=True),
    sa.Column('end_x', sa.Float(), nullable=True),
    sa.Column('end_y', sa.Float(), nullable=True),
    sa.Column('transition_type', sa.String(length=50), nullable=True),
    sa.Column('blend_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_a_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['region_b_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_boundaries_id'), 'region_boundaries', ['id'], unique=False)
    op.create_table('world_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('weather_type', sa.String(length=50), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('particle_effects', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_weather_id'), 'world_weather', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_weather_id'), table_name='world_weather')
    op.drop_table('world_weather')
    op.drop_index(op.f('ix_region_boundaries_id'), table_name='region_boundaries')
    op.drop_table('region_boundaries')
    op.drop_index(op.f('ix_player_positions_id'), table_name='player_positions')
    op.drop_table('player_positions')
    op.drop_index(op.f('ix_fast_travel_points_id'), table_name='fast_travel_points')
    op.drop_table('fast_travel_points')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_day_night_cycle_id'), table_name='day_night_cycle')
    op.drop_table('day_night_cycle')
    # ### end Alembic commands ###
