"""add_housing_and_farming_system

Revision ID: d41dc786d814
Revises: 91963547e3cc
Create Date: 2025-11-18 22:29:37.660864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41dc786d814'
down_revision = '91963547e3cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fishing_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('fish_pool', sa.JSON(), nullable=True),
    sa.Column('rarity_weights', sa.JSON(), nullable=True),
    sa.Column('spot_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fishing_spots_id'), 'fishing_spots', ['id'], unique=False)
    op.create_table('player_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('house_type', sa.String(length=50), nullable=True),
    sa.Column('furniture', sa.JSON(), nullable=True),
    sa.Column('decorations', sa.JSON(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('max_furniture', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_houses_id'), 'player_houses', ['id'], unique=False)
    op.create_table('farm_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(length=50), nullable=True),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('growth_stage', sa.Integer(), nullable=True),
    sa.Column('ready_to_harvest', sa.Boolean(), nullable=True),
    sa.Column('growth_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['player_houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_plots_id'), 'farm_plots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_plots_id'), table_name='farm_plots')
    op.drop_table('farm_plots')
    op.drop_index(op.f('ix_player_houses_id'), table_name='player_houses')
    op.drop_table('player_houses')
    op.drop_index(op.f('ix_fishing_spots_id'), table_name='fishing_spots')
    op.drop_table('fishing_spots')
    # ### end Alembic commands ###
