"""Add card game and dice monsters systems

Revision ID: 91963547e3cc
Revises: dc02ab76c2db
Create Date: 2025-11-18 22:05:37.371443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91963547e3cc'
down_revision = 'dc02ab76c2db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('faction', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('top_value', sa.Integer(), nullable=True),
    sa.Column('right_value', sa.Integer(), nullable=True),
    sa.Column('bottom_value', sa.Integer(), nullable=True),
    sa.Column('left_value', sa.Integer(), nullable=True),
    sa.Column('mana_cost', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('effect_type', sa.String(length=50), nullable=True),
    sa.Column('effect_description', sa.Text(), nullable=True),
    sa.Column('effect_script', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlock_level', sa.Integer(), nullable=True),
    sa.Column('unlock_quest_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('dice_monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monster_type', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('dice_level', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('movement', sa.Integer(), nullable=True),
    sa.Column('summon_cost', sa.Integer(), nullable=True),
    sa.Column('crest_type', sa.String(length=20), nullable=False),
    sa.Column('ability_name', sa.String(length=100), nullable=True),
    sa.Column('ability_description', sa.Text(), nullable=True),
    sa.Column('ability_script', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlock_level', sa.Integer(), nullable=True),
    sa.Column('unlock_quest_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dice_monsters_id'), 'dice_monsters', ['id'], unique=False)
    op.create_table('card_game_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=True),
    sa.Column('rank_tier', sa.String(length=20), nullable=True),
    sa.Column('ranked_wins', sa.Integer(), nullable=True),
    sa.Column('ranked_losses', sa.Integer(), nullable=True),
    sa.Column('ranked_draws', sa.Integer(), nullable=True),
    sa.Column('win_streak', sa.Integer(), nullable=True),
    sa.Column('best_win_streak', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('season_high_rank', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_card_game_rankings_id'), 'card_game_rankings', ['id'], unique=False)
    op.create_table('dice_duel_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('is_ranked', sa.Boolean(), nullable=True),
    sa.Column('is_vs_npc', sa.Boolean(), nullable=True),
    sa.Column('npc_name', sa.String(length=100), nullable=True),
    sa.Column('player1_starting_hp', sa.Integer(), nullable=True),
    sa.Column('player2_starting_hp', sa.Integer(), nullable=True),
    sa.Column('player1_final_hp', sa.Integer(), nullable=True),
    sa.Column('player2_final_hp', sa.Integer(), nullable=True),
    sa.Column('player1_dice_pool', sa.JSON(), nullable=False),
    sa.Column('player2_dice_pool', sa.JSON(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('turns_played', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('final_board', sa.JSON(), nullable=True),
    sa.Column('total_dice_rolled', sa.Integer(), nullable=True),
    sa.Column('total_monsters_summoned', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('dice_won', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dice_duel_matches_id'), 'dice_duel_matches', ['id'], unique=False)
    op.create_table('player_card_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('copies_owned', sa.Integer(), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=True),
    sa.Column('times_played', sa.Integer(), nullable=True),
    sa.Column('times_won_with', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_card_collections_id'), 'player_card_collections', ['id'], unique=False)
    op.create_table('player_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=100), nullable=False),
    sa.Column('faction', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_decks_id'), 'player_decks', ['id'], unique=False)
    op.create_table('player_dice_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('dice_monster_id', sa.Integer(), nullable=False),
    sa.Column('copies_owned', sa.Integer(), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=True),
    sa.Column('times_summoned', sa.Integer(), nullable=True),
    sa.Column('times_won_with', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dice_monster_id'], ['dice_monsters.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_dice_collections_id'), 'player_dice_collections', ['id'], unique=False)
    op.create_table('card_game_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.String(length=20), nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=True),
    sa.Column('is_vs_npc', sa.Boolean(), nullable=True),
    sa.Column('npc_name', sa.String(length=100), nullable=True),
    sa.Column('player1_deck_id', sa.Integer(), nullable=True),
    sa.Column('player2_deck_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('turns_played', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('final_board', sa.JSON(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('cards_won', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player1_deck_id'], ['player_decks.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_deck_id'], ['player_decks.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_game_matches_id'), 'card_game_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_game_matches_id'), table_name='card_game_matches')
    op.drop_table('card_game_matches')
    op.drop_index(op.f('ix_player_dice_collections_id'), table_name='player_dice_collections')
    op.drop_table('player_dice_collections')
    op.drop_index(op.f('ix_player_decks_id'), table_name='player_decks')
    op.drop_table('player_decks')
    op.drop_index(op.f('ix_player_card_collections_id'), table_name='player_card_collections')
    op.drop_table('player_card_collections')
    op.drop_index(op.f('ix_dice_duel_matches_id'), table_name='dice_duel_matches')
    op.drop_table('dice_duel_matches')
    op.drop_index(op.f('ix_card_game_rankings_id'), table_name='card_game_rankings')
    op.drop_table('card_game_rankings')
    op.drop_index(op.f('ix_dice_monsters_id'), table_name='dice_monsters')
    op.drop_table('dice_monsters')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
