"""
Najika v3 – core implementation
This module provides a simple memory system, personality engine and a text-based
interface for interacting with the Najika AI companion. It is inspired by the
specifications from the project documents but avoids explicit content.  The
design prioritizes modularity so that the core can remain stable while
extensions or UI layers can be added later.

Classes:
    NajikaMemory: stores and retrieves conversational history with context tags
    NajikaPersonality: applies personality traits to generate responses
    NajikaInterface: basic CLI chat loop tying memory and personality together
    NajikaStorage: helper for saving persistent memory to disk

This file is intended to be run directly or imported by a larger application.
It uses only the Python standard library.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Tuple


class NajikaMemory:
    """A simple memory system for storing interactions.

    The memory consists of short-term (session) and long-term storage.
    Each entry includes the user's input, Najika's response, an emotion score
    and extracted context tags. Long-term memory is persisted across sessions
    using NajikaStorage.
    """

    def __init__(self) -> None:
        # Current session interactions (not persisted)
        self.short_term: List[Dict[str, object]] = []
        # Persistent storage loaded/saved via NajikaStorage
        self.long_term: List[Dict[str, object]] = []
        # Optional emotion labels indexed by interaction index
        self.emotional_tags: Dict[int, float] = {}

    def store_interaction(self, user_input: str, najika_response: str, emotion_level: float) -> None:
        """Stores a conversational exchange into long-term memory.

        Arguments:
            user_input: The text entered by the user
            najika_response: The response generated by Najika
            emotion_level: A numeric indicator of emotional intensity
        """
        entry = {
            "timestamp": datetime.now().isoformat(),
            "user": user_input,
            "najika": najika_response,
            "emotion": emotion_level,
            "context_tags": self.extract_context(user_input),
        }
        self.long_term.append(entry)
        self.short_term.append(entry)

    def recall_similar(self, current_input: str, threshold: float = 0.5) -> List[Dict[str, object]]:
        """Returns past interactions with a similarity above the threshold.

        A simple Jaccard similarity based on word overlap is used to find
        approximate matches.  More sophisticated algorithms could be applied.

        Arguments:
            current_input: The current user input
            threshold: Minimum similarity score to be considered relevant

        Returns:
            A list of memory entries similar to the current input
        """
        results: List[Dict[str, object]] = []
        current_tokens = set(current_input.lower().split())
        for memory in self.long_term:
            previous_tokens = set(str(memory["user"]).lower().split())
            similarity = self._jaccard_similarity(current_tokens, previous_tokens)
            if similarity >= threshold:
                results.append(memory)
        return results

    def extract_context(self, text: str) -> List[str]:
        """Extracts simple context tags from input.

        This implementation tags whether the text contains certain keywords
        (e.g. requesting an explosion or asking a strategic question).  These
        tags can be used by the personality engine to influence responses.
        """
        tags: List[str] = []
        lowered = text.lower()
        if "explosion" in lowered:
            tags.append("explosion")
        if any(q in lowered for q in ["how", "why", "what", "strategy", "plan"]):
            tags.append("question")
        if "status" in lowered:
            tags.append("status_request")
        return tags

    @staticmethod
    def _jaccard_similarity(set1: set, set2: set) -> float:
        """Calculates the Jaccard similarity between two sets of tokens."""
        if not set1 and not set2:
            return 1.0
        intersection = set1.intersection(set2)
        union = set1.union(set2)
        return len(intersection) / len(union) if union else 0.0


class NajikaPersonality:
    """Personality engine that shapes Najika's responses.

    Traits can be adjusted to modulate the degree of explosiveness, logic,
    protectiveness, and playfulness.  The generator uses simple rules to
    transform a base response into Najika's style.
    """

    def __init__(self, traits: Optional[Dict[str, float]] = None) -> None:
        # Default trait values inspired by Megumin (chaotic, explosive) and
        # Shiro (logical, possessive).
        self.traits = traits or {
            "megumin_chaos": 0.8,
            "shiro_logic": 0.7,
            "protective": 0.9,
            "playful": 0.85,
        }

    def process_input(self, input_text: str) -> str:
        """Processes user input and returns a neutral base response.

        In a more complex system, this would interface with a language model.
        Here we simply echo the input acknowledging receipt.
        """
        return f"Ich habe verstanden: '{input_text}'."

    def is_strategic_question(self, input_text: str) -> bool:
        """Simple heuristic to check if an input is strategic in nature."""
        keywords = ["wie", "warum", "was", "strategie", "plan"]
        return any(word in input_text.lower() for word in keywords)

    def generate_response(self, input_text: str, memory_context: List[Dict[str, object]]) -> str:
        """Generates a response based on the input and memory context.

        The method applies Najika's trait weights to modify the tone of the
        response.  It reacts to keywords such as "explosion" and to strategic
        questions.
        """
        base_response = self.process_input(input_text)
        # Determine style additions
        response_parts: List[str] = []

        # Explosive enthusiasm
        if "explosion" in input_text.lower():
            enthusiasm = "EXPLOSION! ✨ " if self.traits.get("megumin_chaos", 0) > 0.5 else "Boom! "
            response_parts.append(enthusiasm)

        # Strategic contemplation
        if self.is_strategic_question(input_text):
            if self.traits.get("shiro_logic", 0) > 0.5:
                response_parts.append("Lass mich kurz nachdenken… ")

        # Protective tone when past interactions show danger or high emotion
        if any("danger" in mem.get("context_tags", []) for mem in memory_context):
            if self.traits.get("protective", 0) > 0.5:
                response_parts.append("Ich werde dich beschützen, vertraue mir. ")

        # Base response appended with playful flair
        response_parts.append(base_response)

        # Add playful ending
        if self.traits.get("playful", 0) > 0.5:
            response_parts.append(" *zwinkert*")

        return "".join(response_parts)


class NajikaInterface:
    """Simple command-line interface for interacting with Najika.

    This loop reads user input until the user types an exit command. It
    integrates the memory and personality systems.  For GUI or web
    integration, this class could be refactored into asynchronous handlers.
    """

    def __init__(self, storage: Optional['NajikaStorage'] = None) -> None:
        self.memory = NajikaMemory()
        self.personality = NajikaPersonality()
        self.storage = storage or NajikaStorage()
        # Load persisted memory if available
        self.load_memory()

    def load_memory(self) -> None:
        """Loads long-term memory from storage, if present."""
        loaded = self.storage.load_memories()
        if loaded:
            self.memory.long_term = loaded

    def save_memory(self) -> None:
        """Saves current long-term memory to persistent storage."""
        self.storage.save_memories(self.memory.long_term)

    def get_emotion_level(self) -> float:
        """Dummy emotion detection placeholder.

        In a realistic setup, this could analyze voice, text or sensor data to
        assign an emotion intensity. Here we default to a neutral value.
        """
        return 0.5

    def chat_loop(self) -> None:
        """Runs an interactive chat session in the console."""
        print("🌟 Najika ist online! Tippe 'exit' zum Beenden. 🌟")
        while True:
            user_input = input("Du: ")
            if user_input.lower() in {"exit", "bye", "tschüss"}:
                print("Najika: Bis bald! ✨ *Explosion als Abschied*")
                break
            # Recall similar past interactions for context
            context = self.memory.recall_similar(user_input)
            # Generate response via personality engine
            response = self.personality.generate_response(user_input, context)
            # Store interaction
            self.memory.store_interaction(user_input, response, self.get_emotion_level())
            # Display response
            print(f"Najika: {response}")
        # Persist memory at the end of the session
        self.save_memory()


class NajikaStorage:
    """Handles persistence of Najika's memories and configuration.

    Files are saved in a configurable base directory.  By default, this
    class uses a 'NajikaAI' directory in the user's home folder.  The
    directory structure is created on first use.  Memories are stored in
    JSON format.  Additional configuration or log files can be added later.
    """

    def __init__(self, base_path: Optional[str] = None) -> None:
        # Default to a directory in the user's home folder
        if base_path is None:
            home = os.path.expanduser("~")
            base_path = os.path.join(home, "NajikaAI")
        self.base_path = base_path
        self.memory_path = os.path.join(self.base_path, "memory")
        self.config_path = os.path.join(self.base_path, "config")
        self.log_path = os.path.join(self.base_path, "logs")
        self.backup_path = os.path.join(self.base_path, "backups")
        # Ensure directories exist
        self._ensure_directories()

    def _ensure_directories(self) -> None:
        """Creates necessary directories if they do not exist."""
        for path in [self.base_path, self.memory_path, self.config_path, self.log_path, self.backup_path]:
            os.makedirs(path, exist_ok=True)

    def load_memories(self) -> List[Dict[str, object]]:
        """Loads memories from disk if the file exists."""
        file_path = os.path.join(self.memory_path, "memories.json")
        if not os.path.exists(file_path):
            return []
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return []

    def save_memories(self, memories: List[Dict[str, object]]) -> None:
        """Saves a list of memory entries to disk."""
        file_path = os.path.join(self.memory_path, "memories.json")
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(memories, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    # Start interactive session if run directly
    interface = NajikaInterface()
    interface.chat_loop()